/**
 * Database Schema - Comprehensive Workflow Automation Platform
 *
 * This schema defines the complete data model for the Sim workflow automation platform,
 * including user management, workflow orchestration, knowledge bases, collaboration features,
 * and extensible registry system for custom tools and blocks.
 *
 * ARCHITECTURE OVERVIEW:
 * - User Management: Authentication, sessions, organizations, workspaces
 * - Workflow Engine: Workflows, blocks, edges, execution tracking
 * - Knowledge System: RAG-enabled knowledge bases with vector embeddings
 * - Collaboration: Real-time collaborative editing with operational transforms
 * - Extensibility: Dynamic tool and block registry system
 * - Versioning: Comprehensive workflow version control and change tracking
 *
 * PERFORMANCE CONSIDERATIONS:
 * - Strategic indexing for high-traffic queries
 * - JSONB for flexible document storage
 * - Vector indexes for similarity search (HNSW)
 * - Full-text search with PostgreSQL tsvector
 * - Connection pooling optimized for serverless architecture
 *
 * DATABASE TECHNOLOGIES:
 * - PostgreSQL 15+ with pgvector extension
 * - Drizzle ORM for type-safe database operations
 * - HNSW indexes for vector similarity search
 * - GIN indexes for JSONB and full-text search
 * - Optimized for Supabase deployment
 */

import { type SQL, sql } from 'drizzle-orm'
import {
  boolean,
  check,
  customType,
  decimal,
  index,
  integer,
  json,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  vector,
} from 'drizzle-orm/pg-core'
import { DEFAULT_FREE_CREDITS, TAG_SLOTS } from './consts'

/**
 * Custom PostgreSQL tsvector type for full-text search functionality
 *
 * Used for search indexes on text content, particularly for:
 * - Knowledge base document content
 * - Workflow descriptions and names
 * - Chat messages and feedback
 *
 * Performance: Enables fast full-text search queries with ranking
 */
export const tsvector = customType<{
  data: string
}>({
  dataType() {
    return `tsvector`
  },
})

// ========================
// AUTHENTICATION & USER MANAGEMENT
// ========================

/**
 * Users table - Core user identity and profile information
 *
 * Serves as the foundation for all user-related functionality including:
 * - Authentication and session management
 * - Workflow ownership and permissions
 * - Billing and subscription tracking
 * - Organization membership
 *
 * RELATIONSHIPS:
 * - One-to-many: workflows, sessions, organizations
 * - One-to-one: userStats, settings, environment
 *
 * INDEXES: Automatic on primary key and unique email
 * CONSTRAINTS: Email must be unique across all users
 */
export const user = pgTable('user', {
  id: text('id').primaryKey(), // UUID format - generated by auth provider
  name: text('name').notNull(), // Display name for UI and collaboration
  email: text('email').notNull().unique(), // Primary identifier for login
  emailVerified: boolean('email_verified').notNull(), // Email verification status for security
  image: text('image'), // Profile picture URL (optional)
  createdAt: timestamp('created_at').notNull(), // Account creation timestamp
  updatedAt: timestamp('updated_at').notNull(), // Last profile update
  stripeCustomerId: text('stripe_customer_id'), // Stripe customer ID for billing
})

/**
 * Sessions table - User authentication sessions
 *
 * Manages active user sessions with security tracking and context.
 * Each session represents an authenticated user connection.
 *
 * SECURITY FEATURES:
 * - Session expiration for automatic logout
 * - IP address and user agent tracking for security analysis
 * - Cascade delete when user is removed
 * - Unique token constraint prevents session hijacking
 *
 * CONTEXT TRACKING:
 * - Active organization for multi-tenant workflows
 * - Device and location information for audit trails
 */
export const session = pgTable('session', {
  id: text('id').primaryKey(), // Session identifier
  expiresAt: timestamp('expires_at').notNull(), // Automatic session expiration
  token: text('token').notNull().unique(), // Secure session token (JWT/opaque)
  createdAt: timestamp('created_at').notNull(), // Session start time
  updatedAt: timestamp('updated_at').notNull(), // Last activity update
  ipAddress: text('ip_address'), // Client IP for security monitoring
  userAgent: text('user_agent'), // Browser/device information
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }), // Session owner
  activeOrganizationId: text('active_organization_id').references(() => organization.id, {
    onDelete: 'set null', // Preserve session if organization deleted
  }), // Current organization context
})

/**
 * Accounts table - OAuth provider connections and credentials
 *
 * Manages multiple authentication methods per user including:
 * - OAuth providers (Google, GitHub, Microsoft, etc.)
 * - Local password authentication
 * - Token refresh and expiration handling
 *
 * SECURITY:
 * - Tokens are encrypted at rest
 * - Cascade delete removes all provider connections when user deleted
 * - Supports multiple providers per user for flexibility
 *
 * TOKEN MANAGEMENT:
 * - Access tokens for API calls to third-party services
 * - Refresh tokens for automatic token renewal
 * - Expiration tracking for proactive refresh
 */
export const account = pgTable('account', {
  id: text('id').primaryKey(), // Account connection identifier
  accountId: text('account_id').notNull(), // Provider's user ID (e.g., Google user ID)
  providerId: text('provider_id').notNull(), // OAuth provider name (google, github, etc.)
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }), // Connected user
  accessToken: text('access_token'), // OAuth access token (encrypted)
  refreshToken: text('refresh_token'), // OAuth refresh token (encrypted)
  idToken: text('id_token'), // OIDC ID token for user info
  accessTokenExpiresAt: timestamp('access_token_expires_at'), // Token expiration
  refreshTokenExpiresAt: timestamp('refresh_token_expires_at'), // Refresh expiration
  scope: text('scope'), // Granted OAuth scopes
  password: text('password'), // Hashed password for local auth
  createdAt: timestamp('created_at').notNull(), // Connection established
  updatedAt: timestamp('updated_at').notNull(), // Last credential update
})

/**
 * Verification table - Email verification and password reset tokens
 *
 * Handles secure verification processes including:
 * - Email address verification for new accounts
 * - Password reset token validation
 * - Magic link authentication
 * - Two-factor authentication codes
 *
 * SECURITY:
 * - Time-limited tokens prevent replay attacks
 * - Secure random value generation
 * - Automatic cleanup of expired tokens
 */
export const verification = pgTable('verification', {
  id: text('id').primaryKey(), // Verification request ID
  identifier: text('identifier').notNull(), // Email or phone number being verified
  value: text('value').notNull(), // Verification token/code (hashed)
  expiresAt: timestamp('expires_at').notNull(), // Token expiration for security
  createdAt: timestamp('created_at'), // Verification request created
  updatedAt: timestamp('updated_at'), // Last update (e.g., verification attempt)
})

// ========================
// WORKFLOW MANAGEMENT SYSTEM
// ========================

/**
 * Workflow Folders table - Hierarchical organization of workflows
 *
 * Provides folder-based organization within workspaces, supporting:
 * - Nested folder structures (unlimited depth)
 * - Visual organization with colors and expansion state
 * - Drag-and-drop reordering with sort positions
 * - Workspace-scoped folder isolation
 *
 * HIERARCHY FEATURES:
 * - Self-referencing parentId for nested folders
 * - sortOrder for consistent UI ordering
 * - isExpanded for UI state persistence
 *
 * PERFORMANCE INDEXES:
 * - Composite indexes for folder tree queries
 * - Optimized for workspace folder listing
 * - Parent-child relationship queries
 */
export const workflowFolder = pgTable(
  'workflow_folder',
  {
    id: text('id').primaryKey(), // Folder unique identifier
    name: text('name').notNull(), // User-defined folder name
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }), // Folder owner
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }), // Workspace isolation
    parentId: text('parent_id'), // Parent folder ID (null for root folders)
    color: text('color').default('#6B7280'), // UI color theme for visual organization
    isExpanded: boolean('is_expanded').notNull().default(true), // UI expansion state
    sortOrder: integer('sort_order').notNull().default(0), // Position within parent
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    // Index for loading user's folders across workspaces
    userIdx: index('workflow_folder_user_idx').on(table.userId),
    // Index for workspace folder tree queries
    workspaceParentIdx: index('workflow_folder_workspace_parent_idx').on(
      table.workspaceId,
      table.parentId
    ),
    // Index for ordered folder listing within parent
    parentSortIdx: index('workflow_folder_parent_sort_idx').on(table.parentId, table.sortOrder),
  })
)

/**
 * Workflows table - Core workflow definitions and metadata
 *
 * Central table for workflow automation definitions containing:
 * - Workflow metadata (name, description, visual styling)
 * - Deployment state and production configuration
 * - Collaboration settings and shared access
 * - Usage analytics and execution tracking
 * - Marketplace publishing information
 *
 * DEPLOYMENT FEATURES:
 * - isDeployed flag for production readiness
 * - deployedState snapshot for rollback capability
 * - pinnedApiKey for stable API access
 *
 * COLLABORATION:
 * - collaborators JSON array for shared editing
 * - workspace isolation for team boundaries
 * - folder organization for project structure
 *
 * ANALYTICS:
 * - runCount for usage metrics
 * - lastRunAt for activity tracking
 * - Performance monitoring integration
 */
export const workflow = pgTable(
  'workflow',
  {
    id: text('id').primaryKey(), // Workflow unique identifier
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }), // Workflow owner
    workspaceId: text('workspace_id').references(() => workspace.id, { onDelete: 'cascade' }), // Team workspace
    folderId: text('folder_id').references(() => workflowFolder.id, { onDelete: 'set null' }), // Organization folder
    name: text('name').notNull(), // User-defined workflow name
    description: text('description'), // Workflow purpose description
    color: text('color').notNull().default('#3972F6'), // UI theme color
    lastSynced: timestamp('last_synced').notNull(), // Last editor save timestamp
    createdAt: timestamp('created_at').notNull(), // Workflow creation time
    updatedAt: timestamp('updated_at').notNull(), // Last modification time
    isDeployed: boolean('is_deployed').notNull().default(false), // Production deployment status
    deployedState: json('deployed_state'), // Snapshot of deployed version
    deployedAt: timestamp('deployed_at'), // Production deployment timestamp
    pinnedApiKey: text('pinned_api_key'), // Stable API key for external integrations
    collaborators: json('collaborators').notNull().default('[]'), // Shared editor access list
    runCount: integer('run_count').notNull().default(0), // Total execution counter
    lastRunAt: timestamp('last_run_at'), // Most recent execution timestamp
    variables: json('variables').default('{}'), // Workflow-level variables and configuration
    isPublished: boolean('is_published').notNull().default(false), // Marketplace visibility
    marketplaceData: json('marketplace_data'), // Marketplace listing information
  },
  (table) => ({
    // Index for user's workflow dashboard
    userIdIdx: index('workflow_user_id_idx').on(table.userId),
    // Index for workspace workflow listing
    workspaceIdIdx: index('workflow_workspace_id_idx').on(table.workspaceId),
    // Composite index for user workflows within workspace
    userWorkspaceIdx: index('workflow_user_workspace_idx').on(table.userId, table.workspaceId),
  })
)

/**
 * Workflow Blocks table - Individual automation components
 *
 * Represents the building blocks of workflow automation including:
 * - Block type and configuration (agents, APIs, functions, etc.)
 * - Visual positioning and layout properties
 * - Hierarchical relationships (parent-child nesting)
 * - Dynamic configuration and output handling
 *
 * BLOCK TYPES:
 * - 'starter': Entry points and triggers
 * - 'agent': AI agent interactions
 * - 'api': HTTP API calls and integrations
 * - 'function': Custom code execution
 * - 'condition': Logic branching
 * - 'loop': Iteration constructs
 *
 * LAYOUT SYSTEM:
 * - positionX/Y: Canvas coordinates for visual editor
 * - height: Dynamic block sizing
 * - isWide: Expanded layout mode
 * - horizontalHandles: Connection point orientation
 *
 * CONFIGURATION:
 * - data: Block-specific settings and parameters
 * - subBlocks: Nested component definitions
 * - outputs: Runtime output configuration
 */
export const workflowBlocks = pgTable(
  'workflow_blocks',
  {
    id: text('id').primaryKey(), // Block unique identifier
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }), // Parent workflow

    type: text('type').notNull(), // Block category: 'starter', 'agent', 'api', 'function'
    name: text('name').notNull(), // User-defined block name for identification

    // Visual positioning and layout properties
    positionX: decimal('position_x').notNull(), // Canvas X coordinate
    positionY: decimal('position_y').notNull(), // Canvas Y coordinate

    // Block state and behavior flags
    enabled: boolean('enabled').notNull().default(true), // Block execution state
    horizontalHandles: boolean('horizontal_handles').notNull().default(true), // Connection orientation
    isWide: boolean('is_wide').notNull().default(false), // Expanded display mode
    advancedMode: boolean('advanced_mode').notNull().default(false), // Advanced configuration UI
    triggerMode: boolean('trigger_mode').notNull().default(false), // Trigger-based execution
    height: decimal('height').notNull().default('0'), // Dynamic block height

    // Configuration and runtime data (JSONB for flexible structure)
    subBlocks: jsonb('sub_blocks').notNull().default('{}'), // Nested component definitions
    outputs: jsonb('outputs').notNull().default('{}'), // Output port configuration
    data: jsonb('data').default('{}'), // Block-specific settings and parameters

    // Hierarchical relationships
    parentId: text('parent_id'), // Parent block for nesting (null for root blocks)
    extent: text('extent'), // Extent type: 'parent', 'subflow', or null

    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    // Primary index for workflow block queries
    workflowIdIdx: index('workflow_blocks_workflow_id_idx').on(table.workflowId),
    // Index for hierarchical block relationships
    parentIdIdx: index('workflow_blocks_parent_id_idx').on(table.parentId),
    // Composite index for workflow hierarchy queries
    workflowParentIdx: index('workflow_blocks_workflow_parent_idx').on(
      table.workflowId,
      table.parentId
    ),
    // Index for block type filtering and analytics
    workflowTypeIdx: index('workflow_blocks_workflow_type_idx').on(table.workflowId, table.type),
  })
)

/**
 * Workflow Edges table - Block connections and data flow
 *
 * Defines the connections between workflow blocks, representing:
 * - Data flow direction (source to target)
 * - Specific connection points (handles) on blocks
 * - Execution order and dependencies
 * - Conditional routing paths
 *
 * EXECUTION MODEL:
 * - Edges determine workflow execution sequence
 * - Data flows from source outputs to target inputs
 * - Multiple edges can originate from one source
 * - Handles specify exact connection points
 *
 * HANDLE SYSTEM:
 * - sourceHandle: Output port identifier on source block
 * - targetHandle: Input port identifier on target block
 * - Enables multiple input/output connections per block
 * - Supports conditional routing and parallel execution
 *
 * PERFORMANCE:
 * - Indexes optimized for execution path queries
 * - Cascade delete maintains referential integrity
 * - Fast lookup for block dependency resolution
 */
export const workflowEdges = pgTable(
  'workflow_edges',
  {
    id: text('id').primaryKey(), // Edge unique identifier
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }), // Parent workflow

    // Connection endpoints
    sourceBlockId: text('source_block_id')
      .notNull()
      .references(() => workflowBlocks.id, { onDelete: 'cascade' }), // Data origin block
    targetBlockId: text('target_block_id')
      .notNull()
      .references(() => workflowBlocks.id, { onDelete: 'cascade' }), // Data destination block
    sourceHandle: text('source_handle'), // Specific output port on source block
    targetHandle: text('target_handle'), // Specific input port on target block

    createdAt: timestamp('created_at').notNull().defaultNow(), // Edge creation time
  },
  (table) => ({
    // Primary index for workflow edge queries
    workflowIdIdx: index('workflow_edges_workflow_id_idx').on(table.workflowId),
    // Index for finding outgoing connections from a block
    sourceBlockIdx: index('workflow_edges_source_block_idx').on(table.sourceBlockId),
    // Index for finding incoming connections to a block
    targetBlockIdx: index('workflow_edges_target_block_idx').on(table.targetBlockId),
    // Composite index for workflow execution path analysis
    workflowSourceIdx: index('workflow_edges_workflow_source_idx').on(
      table.workflowId,
      table.sourceBlockId
    ),
    // Composite index for workflow dependency resolution
    workflowTargetIdx: index('workflow_edges_workflow_target_idx').on(
      table.workflowId,
      table.targetBlockId
    ),
  })
)

export const workflowSubflows = pgTable(
  'workflow_subflows',
  {
    id: text('id').primaryKey(),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),

    type: text('type').notNull(), // 'loop' or 'parallel'
    config: jsonb('config').notNull().default('{}'),

    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    workflowIdIdx: index('workflow_subflows_workflow_id_idx').on(table.workflowId),
    workflowTypeIdx: index('workflow_subflows_workflow_type_idx').on(table.workflowId, table.type),
  })
)

export const waitlist = pgTable('waitlist', {
  id: text('id').primaryKey(),
  email: text('email').notNull().unique(),
  status: text('status').notNull().default('pending'), // pending, approved, rejected
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const workflowExecutionSnapshots = pgTable(
  'workflow_execution_snapshots',
  {
    id: text('id').primaryKey(),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),
    stateHash: text('state_hash').notNull(),
    stateData: jsonb('state_data').notNull(),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (table) => ({
    workflowIdIdx: index('workflow_snapshots_workflow_id_idx').on(table.workflowId),
    stateHashIdx: index('workflow_snapshots_hash_idx').on(table.stateHash),
    workflowHashUnique: uniqueIndex('workflow_snapshots_workflow_hash_idx').on(
      table.workflowId,
      table.stateHash
    ),
    createdAtIdx: index('workflow_snapshots_created_at_idx').on(table.createdAt),
  })
)

export const workflowExecutionLogs = pgTable(
  'workflow_execution_logs',
  {
    id: text('id').primaryKey(),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),
    executionId: text('execution_id').notNull(),
    stateSnapshotId: text('state_snapshot_id')
      .notNull()
      .references(() => workflowExecutionSnapshots.id),

    level: text('level').notNull(), // 'info', 'error'
    trigger: text('trigger').notNull(), // 'api', 'webhook', 'schedule', 'manual', 'chat'

    startedAt: timestamp('started_at').notNull(),
    endedAt: timestamp('ended_at'),
    totalDurationMs: integer('total_duration_ms'),

    executionData: jsonb('execution_data').notNull().default('{}'),
    cost: jsonb('cost'),
    files: jsonb('files'), // File metadata for execution files
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (table) => ({
    workflowIdIdx: index('workflow_execution_logs_workflow_id_idx').on(table.workflowId),
    executionIdIdx: index('workflow_execution_logs_execution_id_idx').on(table.executionId),
    triggerIdx: index('workflow_execution_logs_trigger_idx').on(table.trigger),
    levelIdx: index('workflow_execution_logs_level_idx').on(table.level),
    startedAtIdx: index('workflow_execution_logs_started_at_idx').on(table.startedAt),
    executionIdUnique: uniqueIndex('workflow_execution_logs_execution_id_unique').on(
      table.executionId
    ),
    // Composite index for the new join-based query pattern
    workflowStartedAtIdx: index('workflow_execution_logs_workflow_started_at_idx').on(
      table.workflowId,
      table.startedAt
    ),
  })
)

export const environment = pgTable('environment', {
  id: text('id').primaryKey(), // Use the user id as the key
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' })
    .unique(), // One environment per user
  variables: json('variables').notNull(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const settings = pgTable('settings', {
  id: text('id').primaryKey(), // Use the user id as the key
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' })
    .unique(), // One settings record per user

  // General settings
  theme: text('theme').notNull().default('system'),
  autoConnect: boolean('auto_connect').notNull().default(true),
  autoFillEnvVars: boolean('auto_fill_env_vars').notNull().default(true), // DEPRECATED: autofill feature removed
  autoPan: boolean('auto_pan').notNull().default(true),
  consoleExpandedByDefault: boolean('console_expanded_by_default').notNull().default(true),

  // Privacy settings
  telemetryEnabled: boolean('telemetry_enabled').notNull().default(true),

  // Email preferences
  emailPreferences: json('email_preferences').notNull().default('{}'),

  // Keep general for future flexible settings
  general: json('general').notNull().default('{}'),

  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const workflowSchedule = pgTable(
  'workflow_schedule',
  {
    id: text('id').primaryKey(),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),
    blockId: text('block_id').references(() => workflowBlocks.id, { onDelete: 'cascade' }),
    cronExpression: text('cron_expression'),
    nextRunAt: timestamp('next_run_at'),
    lastRanAt: timestamp('last_ran_at'),
    triggerType: text('trigger_type').notNull(), // "manual", "webhook", "schedule"
    timezone: text('timezone').notNull().default('UTC'),
    failedCount: integer('failed_count').notNull().default(0), // Track consecutive failures
    status: text('status').notNull().default('active'), // 'active' or 'disabled'
    lastFailedAt: timestamp('last_failed_at'), // When the schedule last failed
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => {
    return {
      workflowBlockUnique: uniqueIndex('workflow_schedule_workflow_block_unique').on(
        table.workflowId,
        table.blockId
      ),
    }
  }
)

export const webhook = pgTable(
  'webhook',
  {
    id: text('id').primaryKey(),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),
    blockId: text('block_id').references(() => workflowBlocks.id, { onDelete: 'cascade' }), // ID of the webhook trigger block (nullable for legacy starter block webhooks)
    path: text('path').notNull(),
    provider: text('provider'), // e.g., "whatsapp", "github", etc.
    providerConfig: json('provider_config'), // Store provider-specific configuration
    isActive: boolean('is_active').notNull().default(true),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => {
    return {
      // Ensure webhook paths are unique
      pathIdx: uniqueIndex('path_idx').on(table.path),
    }
  }
)

export const apiKey = pgTable('api_key', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  key: text('key').notNull().unique(),
  lastUsed: timestamp('last_used'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  expiresAt: timestamp('expires_at'),
})

export const marketplace = pgTable('marketplace', {
  id: text('id').primaryKey(),
  workflowId: text('workflow_id')
    .notNull()
    .references(() => workflow.id, { onDelete: 'cascade' }),
  state: json('state').notNull(),
  name: text('name').notNull(),
  description: text('description'),
  authorId: text('author_id')
    .notNull()
    .references(() => user.id),
  authorName: text('author_name').notNull(),
  views: integer('views').notNull().default(0),
  category: text('category'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const userStats = pgTable('user_stats', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' })
    .unique(), // One record per user
  totalManualExecutions: integer('total_manual_executions').notNull().default(0),
  totalApiCalls: integer('total_api_calls').notNull().default(0),
  totalWebhookTriggers: integer('total_webhook_triggers').notNull().default(0),
  totalScheduledExecutions: integer('total_scheduled_executions').notNull().default(0),
  totalChatExecutions: integer('total_chat_executions').notNull().default(0),
  totalTokensUsed: integer('total_tokens_used').notNull().default(0),
  totalCost: decimal('total_cost').notNull().default('0'),
  currentUsageLimit: decimal('current_usage_limit').default(DEFAULT_FREE_CREDITS.toString()), // Default $10 for free plan, null for team/enterprise
  usageLimitUpdatedAt: timestamp('usage_limit_updated_at').defaultNow(),
  // Billing period tracking
  currentPeriodCost: decimal('current_period_cost').notNull().default('0'), // Usage in current billing period
  lastPeriodCost: decimal('last_period_cost').default('0'), // Usage from previous billing period
  // Copilot usage tracking
  totalCopilotCost: decimal('total_copilot_cost').notNull().default('0'),
  totalCopilotTokens: integer('total_copilot_tokens').notNull().default(0),
  totalCopilotCalls: integer('total_copilot_calls').notNull().default(0),
  lastActive: timestamp('last_active').notNull().defaultNow(),
  billingBlocked: boolean('billing_blocked').notNull().default(false),
})

export const customTools = pgTable('custom_tools', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  title: text('title').notNull(),
  schema: json('schema').notNull(),
  code: text('code').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const subscription = pgTable(
  'subscription',
  {
    id: text('id').primaryKey(),
    plan: text('plan').notNull(),
    referenceId: text('reference_id').notNull(),
    stripeCustomerId: text('stripe_customer_id'),
    stripeSubscriptionId: text('stripe_subscription_id'),
    status: text('status'),
    periodStart: timestamp('period_start'),
    periodEnd: timestamp('period_end'),
    cancelAtPeriodEnd: boolean('cancel_at_period_end'),
    seats: integer('seats'),
    trialStart: timestamp('trial_start'),
    trialEnd: timestamp('trial_end'),
    metadata: json('metadata'),
  },
  (table) => ({
    referenceStatusIdx: index('subscription_reference_status_idx').on(
      table.referenceId,
      table.status
    ),
    enterpriseMetadataCheck: check(
      'check_enterprise_metadata',
      sql`plan != 'enterprise' OR metadata IS NOT NULL`
    ),
  })
)

export const userRateLimits = pgTable('user_rate_limits', {
  userId: text('user_id')
    .primaryKey()
    .references(() => user.id, { onDelete: 'cascade' }),
  syncApiRequests: integer('sync_api_requests').notNull().default(0), // Sync API requests counter
  asyncApiRequests: integer('async_api_requests').notNull().default(0), // Async API requests counter
  windowStart: timestamp('window_start').notNull().defaultNow(),
  lastRequestAt: timestamp('last_request_at').notNull().defaultNow(),
  isRateLimited: boolean('is_rate_limited').notNull().default(false),
  rateLimitResetAt: timestamp('rate_limit_reset_at'),
})

export const chat = pgTable(
  'chat',
  {
    id: text('id').primaryKey(),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    subdomain: text('subdomain').notNull(),
    title: text('title').notNull(),
    description: text('description'),
    isActive: boolean('is_active').notNull().default(true),
    customizations: json('customizations').default('{}'), // For UI customization options

    // Authentication options
    authType: text('auth_type').notNull().default('public'), // 'public', 'password', 'email'
    password: text('password'), // Stored hashed, populated when authType is 'password'
    allowedEmails: json('allowed_emails').default('[]'), // Array of allowed emails or domains when authType is 'email'

    // Output configuration
    outputConfigs: json('output_configs').default('[]'), // Array of {blockId, path} objects

    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => {
    return {
      // Ensure subdomains are unique
      subdomainIdx: uniqueIndex('subdomain_idx').on(table.subdomain),
    }
  }
)

export const organization = pgTable('organization', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  slug: text('slug').notNull(),
  logo: text('logo'),
  metadata: json('metadata'),
  orgUsageLimit: decimal('org_usage_limit'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
})

export const member = pgTable('member', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  organizationId: text('organization_id')
    .notNull()
    .references(() => organization.id, { onDelete: 'cascade' }),
  role: text('role').notNull(), // 'admin' or 'member' - team-level permissions only
  createdAt: timestamp('created_at').defaultNow().notNull(),
})

export const invitation = pgTable('invitation', {
  id: text('id').primaryKey(),
  email: text('email').notNull(),
  inviterId: text('inviter_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  organizationId: text('organization_id')
    .notNull()
    .references(() => organization.id, { onDelete: 'cascade' }),
  role: text('role').notNull(),
  status: text('status').notNull(),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
})

export const workspace = pgTable('workspace', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  ownerId: text('owner_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

// Define the permission enum
export const permissionTypeEnum = pgEnum('permission_type', ['admin', 'write', 'read'])

export const workspaceInvitation = pgTable('workspace_invitation', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id')
    .notNull()
    .references(() => workspace.id, { onDelete: 'cascade' }),
  email: text('email').notNull(),
  inviterId: text('inviter_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  role: text('role').notNull().default('member'),
  status: text('status').notNull().default('pending'),
  token: text('token').notNull().unique(),
  permissions: permissionTypeEnum('permissions').notNull().default('admin'),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const permissions = pgTable(
  'permissions',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    entityType: text('entity_type').notNull(), // 'workspace', 'workflow', 'organization', etc.
    entityId: text('entity_id').notNull(), // ID of the workspace, workflow, etc.
    permissionType: permissionTypeEnum('permission_type').notNull(), // Use enum instead of text
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    // Primary access pattern - get all permissions for a user
    userIdIdx: index('permissions_user_id_idx').on(table.userId),

    // Entity-based queries - get all users with permissions on an entity
    entityIdx: index('permissions_entity_idx').on(table.entityType, table.entityId),

    // User + entity type queries - get user's permissions for all workspaces
    userEntityTypeIdx: index('permissions_user_entity_type_idx').on(table.userId, table.entityType),

    // Specific permission checks - does user have specific permission on entity
    userEntityPermissionIdx: index('permissions_user_entity_permission_idx').on(
      table.userId,
      table.entityType,
      table.permissionType
    ),

    // User + specific entity queries - get user's permissions for specific entity
    userEntityIdx: index('permissions_user_entity_idx').on(
      table.userId,
      table.entityType,
      table.entityId
    ),

    // Uniqueness constraint - prevent duplicate permission rows (one permission per user/entity)
    uniquePermissionConstraint: uniqueIndex('permissions_unique_constraint').on(
      table.userId,
      table.entityType,
      table.entityId
    ),
  })
)

export const memory = pgTable(
  'memory',
  {
    id: text('id').primaryKey(),
    workflowId: text('workflow_id').references(() => workflow.id, { onDelete: 'cascade' }),
    key: text('key').notNull(), // Identifier for the memory within its context
    type: text('type').notNull(), // 'agent' or 'raw'
    data: json('data').notNull(), // Stores either agent message data or raw data
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
    deletedAt: timestamp('deleted_at'),
  },
  (table) => {
    return {
      // Add index on key for faster lookups
      keyIdx: index('memory_key_idx').on(table.key),

      // Add index on workflowId for faster filtering
      workflowIdx: index('memory_workflow_idx').on(table.workflowId),

      // Compound unique index to ensure keys are unique per workflow
      uniqueKeyPerWorkflowIdx: uniqueIndex('memory_workflow_key_idx').on(
        table.workflowId,
        table.key
      ),
    }
  }
)

// ========================
// KNOWLEDGE BASE & RAG SYSTEM
// ========================

/**
 * Knowledge Base table - RAG-enabled document collections
 *
 * Central registry for document collections supporting:
 * - Vector similarity search with embeddings
 * - Flexible document tagging and organization
 * - Configurable chunking strategies
 * - Usage tracking and billing integration
 * - Workspace-based access control
 *
 * RAG ARCHITECTURE:
 * - Documents are chunked into embeddings for retrieval
 * - Vector similarity search finds relevant content
 * - Full-text search provides keyword matching
 * - Tag-based filtering enables targeted search
 *
 * EMBEDDING STRATEGY:
 * - text-embedding-3-small: Cost-effective, 1536 dimensions
 * - HNSW indexes for fast similarity search
 * - Configurable chunking for optimal retrieval
 * - Incremental updates with deduplication
 *
 * PERFORMANCE FEATURES:
 * - Token counting for usage billing
 * - Soft delete for data retention
 * - Workspace isolation for security
 * - Optimized indexes for common queries
 */
export const knowledgeBase = pgTable(
  'knowledge_base',
  {
    id: text('id').primaryKey(), // Knowledge base identifier
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }), // Owner for access control
    workspaceId: text('workspace_id').references(() => workspace.id), // Team workspace (optional)
    name: text('name').notNull(), // User-defined collection name
    description: text('description'), // Purpose and content description

    // Usage tracking for billing and analytics
    tokenCount: integer('token_count').notNull().default(0), // Total tokens for cost calculation

    // Vector embedding configuration
    embeddingModel: text('embedding_model').notNull().default('text-embedding-3-small'), // OpenAI model
    embeddingDimension: integer('embedding_dimension').notNull().default(1536), // Vector dimensions

    // Document chunking strategy (JSON for future extensibility)
    chunkingConfig: json('chunking_config')
      .notNull()
      .default('{"maxSize": 1024, "minSize": 1, "overlap": 200}'), // Chunking parameters

    // Soft delete support for data retention
    deletedAt: timestamp('deleted_at'), // Null = active, timestamp = deleted

    // Audit and lifecycle timestamps
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    // Index for user's knowledge bases
    userIdIdx: index('kb_user_id_idx').on(table.userId),
    // Index for workspace knowledge bases
    workspaceIdIdx: index('kb_workspace_id_idx').on(table.workspaceId),
    // Composite index for user workspace queries
    userWorkspaceIdx: index('kb_user_workspace_idx').on(table.userId, table.workspaceId),
    // Index for soft delete filtering
    deletedAtIdx: index('kb_deleted_at_idx').on(table.deletedAt),
  })
)

/**
 * Documents table - Individual files within knowledge bases
 *
 * Manages uploaded documents and their processing pipeline:
 * - File metadata and storage references
 * - Processing status tracking for async workflows
 * - Content statistics for analytics and billing
 * - Tag-based organization and filtering
 * - Enable/disable controls for search inclusion
 *
 * DOCUMENT PROCESSING PIPELINE:
 * 1. Upload: File stored, metadata recorded (pending)
 * 2. Processing: Content extraction, chunking (processing)
 * 3. Embedding: Vector generation for chunks (processing)
 * 4. Indexing: Search index creation (completed)
 * 5. Error Handling: Failure recovery (failed)
 *
 * SUPPORTED FILE TYPES:
 * - PDF documents: Text extraction with layout preservation
 * - Text files: Plain text processing
 * - Word documents: Content extraction
 * - PowerPoint: Slide content processing
 * - Excel: Table and data extraction
 *
 * TAG SYSTEM:
 * - 7 tag slots for flexible categorization
 * - Tags inherited by all document chunks
 * - Fast filtering without JOIN operations
 * - Custom tag definitions per knowledge base
 */
export const document = pgTable(
  'document',
  {
    id: text('id').primaryKey(), // Document identifier
    knowledgeBaseId: text('knowledge_base_id')
      .notNull()
      .references(() => knowledgeBase.id, { onDelete: 'cascade' }), // Parent knowledge base

    // File metadata and storage
    filename: text('filename').notNull(), // Original filename for display
    fileUrl: text('file_url').notNull(), // Storage URL (S3, etc.)
    fileSize: integer('file_size').notNull(), // File size in bytes
    mimeType: text('mime_type').notNull(), // MIME type for processing strategy

    // Content analysis results
    chunkCount: integer('chunk_count').notNull().default(0), // Number of generated chunks
    tokenCount: integer('token_count').notNull().default(0), // Total tokens for billing
    characterCount: integer('character_count').notNull().default(0), // Character count

    // Async processing workflow status
    processingStatus: text('processing_status').notNull().default('pending'), // Workflow state
    processingStartedAt: timestamp('processing_started_at'), // Processing start time
    processingCompletedAt: timestamp('processing_completed_at'), // Completion time
    processingError: text('processing_error'), // Error message if failed

    // Document availability controls
    enabled: boolean('enabled').notNull().default(true), // Include in search results
    deletedAt: timestamp('deleted_at'), // Soft delete timestamp

    // Tag-based categorization system (inherited by chunks)
    tag1: text('tag1'), // Configurable tag slot 1
    tag2: text('tag2'), // Configurable tag slot 2
    tag3: text('tag3'), // Configurable tag slot 3
    tag4: text('tag4'), // Configurable tag slot 4
    tag5: text('tag5'), // Configurable tag slot 5
    tag6: text('tag6'), // Configurable tag slot 6
    tag7: text('tag7'), // Configurable tag slot 7

    // Document lifecycle timestamp
    uploadedAt: timestamp('uploaded_at').notNull().defaultNow(),
  },
  (table) => ({
    // Primary index for knowledge base document listing
    knowledgeBaseIdIdx: index('doc_kb_id_idx').on(table.knowledgeBaseId),
    // Index for filename search and autocomplete
    filenameIdx: index('doc_filename_idx').on(table.filename),
    // Composite index for chronological document listing
    kbUploadedAtIdx: index('doc_kb_uploaded_at_idx').on(table.knowledgeBaseId, table.uploadedAt),
    // Index for processing status monitoring
    processingStatusIdx: index('doc_processing_status_idx').on(
      table.knowledgeBaseId,
      table.processingStatus
    ),
    // Individual tag indexes for fast filtering
    tag1Idx: index('doc_tag1_idx').on(table.tag1),
    tag2Idx: index('doc_tag2_idx').on(table.tag2),
    tag3Idx: index('doc_tag3_idx').on(table.tag3),
    tag4Idx: index('doc_tag4_idx').on(table.tag4),
    tag5Idx: index('doc_tag5_idx').on(table.tag5),
    tag6Idx: index('doc_tag6_idx').on(table.tag6),
    tag7Idx: index('doc_tag7_idx').on(table.tag7),
  })
)

/**
 * Knowledge Base Tag Definitions table - Custom tag schema configuration
 *
 * Defines the meaning and UI presentation of tag slots within each knowledge base:
 * - Maps generic tag slots (tag1, tag2, etc.) to meaningful names
 * - Configures field types for UI components and validation
 * - Enables knowledge base-specific categorization systems
 * - Supports future extensibility with typed tag values
 *
 * DESIGN RATIONALE:
 * - Flexible tagging without schema migrations
 * - User-friendly tag names in UI
 * - Knowledge base isolation for different categorization needs
 * - Future support for structured tag types (dates, numbers)
 *
 * USAGE PATTERNS:
 * - Department tags: "Department", "Team", "Project"
 * - Content types: "Document Type", "Status", "Priority"
 * - Access control: "Sensitivity", "Access Level"
 * - Workflow states: "Review Status", "Approval State"
 *
 * EXTENSIBILITY:
 * - fieldType supports future typed tag values
 * - Validation rules for structured data
 * - UI component selection based on type
 */
export const knowledgeBaseTagDefinitions = pgTable(
  'knowledge_base_tag_definitions',
  {
    id: text('id').primaryKey(), // Tag definition identifier
    knowledgeBaseId: text('knowledge_base_id')
      .notNull()
      .references(() => knowledgeBase.id, { onDelete: 'cascade' }), // Parent knowledge base
    tagSlot: text('tag_slot', {
      enum: TAG_SLOTS, // Must be one of the predefined tag slots
    }).notNull(), // Which tag column this definition applies to
    displayName: text('display_name').notNull(), // Human-readable name for UI
    fieldType: text('field_type').notNull().default('text'), // Field type: 'text', 'date', 'number', 'select'
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    // Ensure each tag slot has only one definition per knowledge base
    kbTagSlotIdx: uniqueIndex('kb_tag_definitions_kb_slot_idx').on(
      table.knowledgeBaseId,
      table.tagSlot
    ),
    // Ensure display names are unique within knowledge base
    kbDisplayNameIdx: uniqueIndex('kb_tag_definitions_kb_display_name_idx').on(
      table.knowledgeBaseId,
      table.displayName
    ),
    // Index for loading all tag definitions for a knowledge base
    kbIdIdx: index('kb_tag_definitions_kb_id_idx').on(table.knowledgeBaseId),
  })
)

export const embedding = pgTable(
  'embedding',
  {
    id: text('id').primaryKey(),
    knowledgeBaseId: text('knowledge_base_id')
      .notNull()
      .references(() => knowledgeBase.id, { onDelete: 'cascade' }),
    documentId: text('document_id')
      .notNull()
      .references(() => document.id, { onDelete: 'cascade' }),

    // Chunk information
    chunkIndex: integer('chunk_index').notNull(),
    chunkHash: text('chunk_hash').notNull(),
    content: text('content').notNull(),
    contentLength: integer('content_length').notNull(),
    tokenCount: integer('token_count').notNull(),

    // Vector embeddings - optimized for text-embedding-3-small with HNSW support
    embedding: vector('embedding', { dimensions: 1536 }), // For text-embedding-3-small
    embeddingModel: text('embedding_model').notNull().default('text-embedding-3-small'),

    // Chunk boundaries and overlap
    startOffset: integer('start_offset').notNull(),
    endOffset: integer('end_offset').notNull(),

    // Tag columns inherited from document for efficient filtering
    tag1: text('tag1'),
    tag2: text('tag2'),
    tag3: text('tag3'),
    tag4: text('tag4'),
    tag5: text('tag5'),
    tag6: text('tag6'),
    tag7: text('tag7'),

    // Chunk state - enable/disable from knowledge base
    enabled: boolean('enabled').notNull().default(true),

    // Full-text search support - generated tsvector column
    contentTsv: tsvector('content_tsv').generatedAlwaysAs(
      (): SQL => sql`to_tsvector('english', ${embedding.content})`
    ),

    // Timestamps
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    // Primary vector search pattern
    kbIdIdx: index('emb_kb_id_idx').on(table.knowledgeBaseId),

    // Document-level access
    docIdIdx: index('emb_doc_id_idx').on(table.documentId),

    // Chunk ordering within documents
    docChunkIdx: uniqueIndex('emb_doc_chunk_idx').on(table.documentId, table.chunkIndex),

    // Model-specific queries for A/B testing or migrations
    kbModelIdx: index('emb_kb_model_idx').on(table.knowledgeBaseId, table.embeddingModel),

    // Enabled state filtering indexes (for chunk enable/disable functionality)
    kbEnabledIdx: index('emb_kb_enabled_idx').on(table.knowledgeBaseId, table.enabled),
    docEnabledIdx: index('emb_doc_enabled_idx').on(table.documentId, table.enabled),

    // Vector similarity search indexes (HNSW) - optimized for small embeddings
    embeddingVectorHnswIdx: index('embedding_vector_hnsw_idx')
      .using('hnsw', table.embedding.op('vector_cosine_ops'))
      .with({
        m: 16,
        ef_construction: 64,
      }),

    // Tag indexes for efficient filtering
    tag1Idx: index('emb_tag1_idx').on(table.tag1),
    tag2Idx: index('emb_tag2_idx').on(table.tag2),
    tag3Idx: index('emb_tag3_idx').on(table.tag3),
    tag4Idx: index('emb_tag4_idx').on(table.tag4),
    tag5Idx: index('emb_tag5_idx').on(table.tag5),
    tag6Idx: index('emb_tag6_idx').on(table.tag6),
    tag7Idx: index('emb_tag7_idx').on(table.tag7),

    // Full-text search index
    contentFtsIdx: index('emb_content_fts_idx').using('gin', table.contentTsv),

    // Ensure embedding exists (simplified since we only support one model)
    embeddingNotNullCheck: check('embedding_not_null_check', sql`"embedding" IS NOT NULL`),
  })
)

export const docsEmbeddings = pgTable(
  'docs_embeddings',
  {
    chunkId: uuid('chunk_id').primaryKey().defaultRandom(),
    chunkText: text('chunk_text').notNull(),
    sourceDocument: text('source_document').notNull(),
    sourceLink: text('source_link').notNull(),
    headerText: text('header_text').notNull(),
    headerLevel: integer('header_level').notNull(),
    tokenCount: integer('token_count').notNull(),

    // Vector embedding - optimized for text-embedding-3-small with HNSW support
    embedding: vector('embedding', { dimensions: 1536 }).notNull(),
    embeddingModel: text('embedding_model').notNull().default('text-embedding-3-small'),

    // Metadata for flexible filtering
    metadata: jsonb('metadata').notNull().default('{}'),

    // Full-text search support - generated tsvector column
    chunkTextTsv: tsvector('chunk_text_tsv').generatedAlwaysAs(
      (): SQL => sql`to_tsvector('english', ${docsEmbeddings.chunkText})`
    ),

    // Timestamps
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    // Source document queries
    sourceDocumentIdx: index('docs_emb_source_document_idx').on(table.sourceDocument),

    // Header level filtering
    headerLevelIdx: index('docs_emb_header_level_idx').on(table.headerLevel),

    // Combined source and header queries
    sourceHeaderIdx: index('docs_emb_source_header_idx').on(
      table.sourceDocument,
      table.headerLevel
    ),

    // Model-specific queries
    modelIdx: index('docs_emb_model_idx').on(table.embeddingModel),

    // Timestamp queries
    createdAtIdx: index('docs_emb_created_at_idx').on(table.createdAt),

    // Vector similarity search indexes (HNSW) - optimized for documentation embeddings
    embeddingVectorHnswIdx: index('docs_embedding_vector_hnsw_idx')
      .using('hnsw', table.embedding.op('vector_cosine_ops'))
      .with({
        m: 16,
        ef_construction: 64,
      }),

    // GIN index for JSONB metadata queries
    metadataGinIdx: index('docs_emb_metadata_gin_idx').using('gin', table.metadata),

    // Full-text search index
    chunkTextFtsIdx: index('docs_emb_chunk_text_fts_idx').using('gin', table.chunkTextTsv),

    // Constraints
    embeddingNotNullCheck: check('docs_embedding_not_null_check', sql`"embedding" IS NOT NULL`),
    headerLevelCheck: check(
      'docs_header_level_check',
      sql`"header_level" >= 1 AND "header_level" <= 6`
    ),
  })
)

export const copilotChats = pgTable(
  'copilot_chats',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),
    title: text('title'),
    messages: jsonb('messages').notNull().default('[]'),
    model: text('model').notNull().default('claude-3-7-sonnet-latest'),
    conversationId: text('conversation_id'),
    previewYaml: text('preview_yaml'), // YAML content for pending workflow preview
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    // Primary access patterns
    userIdIdx: index('copilot_chats_user_id_idx').on(table.userId),
    workflowIdIdx: index('copilot_chats_workflow_id_idx').on(table.workflowId),
    userWorkflowIdx: index('copilot_chats_user_workflow_idx').on(table.userId, table.workflowId),

    // Ordering indexes
    createdAtIdx: index('copilot_chats_created_at_idx').on(table.createdAt),
    updatedAtIdx: index('copilot_chats_updated_at_idx').on(table.updatedAt),
  })
)

export const workflowCheckpoints = pgTable(
  'workflow_checkpoints',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),
    chatId: uuid('chat_id')
      .notNull()
      .references(() => copilotChats.id, { onDelete: 'cascade' }),
    messageId: text('message_id'), // ID of the user message that triggered this checkpoint
    workflowState: json('workflow_state').notNull(), // JSON workflow state
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    // Primary access patterns
    userIdIdx: index('workflow_checkpoints_user_id_idx').on(table.userId),
    workflowIdIdx: index('workflow_checkpoints_workflow_id_idx').on(table.workflowId),
    chatIdIdx: index('workflow_checkpoints_chat_id_idx').on(table.chatId),
    messageIdIdx: index('workflow_checkpoints_message_id_idx').on(table.messageId),

    // Combined indexes for common queries
    userWorkflowIdx: index('workflow_checkpoints_user_workflow_idx').on(
      table.userId,
      table.workflowId
    ),
    workflowChatIdx: index('workflow_checkpoints_workflow_chat_idx').on(
      table.workflowId,
      table.chatId
    ),

    // Ordering indexes
    createdAtIdx: index('workflow_checkpoints_created_at_idx').on(table.createdAt),
    chatCreatedAtIdx: index('workflow_checkpoints_chat_created_at_idx').on(
      table.chatId,
      table.createdAt
    ),
  })
)

export const templates = pgTable(
  'templates',
  {
    id: text('id').primaryKey(),
    workflowId: text('workflow_id').references(() => workflow.id),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    description: text('description'),
    author: text('author').notNull(),
    views: integer('views').notNull().default(0),
    stars: integer('stars').notNull().default(0),
    color: text('color').notNull().default('#3972F6'),
    icon: text('icon').notNull().default('FileText'), // Lucide icon name as string
    category: text('category').notNull(),
    state: jsonb('state').notNull(), // Using jsonb for better performance
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    // Primary access patterns
    workflowIdIdx: index('templates_workflow_id_idx').on(table.workflowId),
    userIdIdx: index('templates_user_id_idx').on(table.userId),
    categoryIdx: index('templates_category_idx').on(table.category),

    // Sorting indexes for popular/trending templates
    viewsIdx: index('templates_views_idx').on(table.views),
    starsIdx: index('templates_stars_idx').on(table.stars),

    // Composite indexes for common queries
    categoryViewsIdx: index('templates_category_views_idx').on(table.category, table.views),
    categoryStarsIdx: index('templates_category_stars_idx').on(table.category, table.stars),
    userCategoryIdx: index('templates_user_category_idx').on(table.userId, table.category),

    // Temporal indexes
    createdAtIdx: index('templates_created_at_idx').on(table.createdAt),
    updatedAtIdx: index('templates_updated_at_idx').on(table.updatedAt),
  })
)

export const templateStars = pgTable(
  'template_stars',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    templateId: text('template_id')
      .notNull()
      .references(() => templates.id, { onDelete: 'cascade' }),
    starredAt: timestamp('starred_at').notNull().defaultNow(),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (table) => ({
    // Primary access patterns
    userIdIdx: index('template_stars_user_id_idx').on(table.userId),
    templateIdIdx: index('template_stars_template_id_idx').on(table.templateId),

    // Composite indexes for common queries
    userTemplateIdx: index('template_stars_user_template_idx').on(table.userId, table.templateId),
    templateUserIdx: index('template_stars_template_user_idx').on(table.templateId, table.userId),

    // Temporal indexes for analytics
    starredAtIdx: index('template_stars_starred_at_idx').on(table.starredAt),
    templateStarredAtIdx: index('template_stars_template_starred_at_idx').on(
      table.templateId,
      table.starredAt
    ),

    // Uniqueness constraint - prevent duplicate stars
    uniqueUserTemplateConstraint: uniqueIndex('template_stars_user_template_unique').on(
      table.userId,
      table.templateId
    ),
  })
)

export const copilotFeedback = pgTable(
  'copilot_feedback',
  {
    feedbackId: uuid('feedback_id').primaryKey().defaultRandom(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    chatId: uuid('chat_id')
      .notNull()
      .references(() => copilotChats.id, { onDelete: 'cascade' }),
    userQuery: text('user_query').notNull(),
    agentResponse: text('agent_response').notNull(),
    isPositive: boolean('is_positive').notNull(),
    feedback: text('feedback'), // Optional feedback text
    workflowYaml: text('workflow_yaml'), // Optional workflow YAML if edit/build workflow was triggered
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    // Access patterns
    userIdIdx: index('copilot_feedback_user_id_idx').on(table.userId),
    chatIdIdx: index('copilot_feedback_chat_id_idx').on(table.chatId),
    userChatIdx: index('copilot_feedback_user_chat_idx').on(table.userId, table.chatId),

    // Query patterns
    isPositiveIdx: index('copilot_feedback_is_positive_idx').on(table.isPositive),

    // Ordering indexes
    createdAtIdx: index('copilot_feedback_created_at_idx').on(table.createdAt),
  })
)

// Workflow Versioning System Tables - Comprehensive version management with semantic versioning
export const workflowVersions: any = pgTable(
  'workflow_versions',
  {
    id: text('id').primaryKey(),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),

    // Semantic versioning fields
    versionNumber: text('version_number').notNull(), // e.g., "1.2.3"
    versionMajor: integer('version_major').notNull().default(0),
    versionMinor: integer('version_minor').notNull().default(0),
    versionPatch: integer('version_patch').notNull().default(1),

    // Version metadata
    versionType: text('version_type').notNull().default('auto'), // 'auto', 'manual', 'checkpoint', 'branch'
    versionTag: text('version_tag'), // optional tag like 'stable', 'beta', 'production'
    versionDescription: text('version_description'),
    changeSummary: jsonb('change_summary').default('{}'),

    // Workflow state storage
    workflowState: jsonb('workflow_state').notNull(),
    stateHash: text('state_hash').notNull(),
    stateSize: integer('state_size').notNull(),
    compressionType: text('compression_type').default('none'), // 'none', 'gzip', 'delta'

    // Version relationships
    parentVersionId: text('parent_version_id').references(() => workflowVersions.id),
    branchName: text('branch_name').default('main'),

    // Audit fields
    createdByUserId: text('created_by_user_id').references(() => user.id),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),

    // Status flags
    isCurrent: boolean('is_current').default(false),
    isDeployed: boolean('is_deployed').default(false),
    deployedAt: timestamp('deployed_at'),

    // Performance metadata
    creationDurationMs: integer('creation_duration_ms'),
    serializationTimeMs: integer('serialization_time_ms'),
  },
  (table) => ({
    workflowIdIdx: index('workflow_versions_workflow_id_idx').on(table.workflowId),
    versionNumberIdx: index('workflow_versions_version_number_idx').on(
      table.workflowId,
      table.versionMajor.desc(),
      table.versionMinor.desc(),
      table.versionPatch.desc()
    ),
    createdAtIdx: index('workflow_versions_created_at_idx').on(
      table.workflowId,
      table.createdAt.desc()
    ),
    currentIdx: index('workflow_versions_current_idx').on(table.workflowId, table.isCurrent),
    deployedIdx: index('workflow_versions_deployed_idx').on(table.workflowId, table.isDeployed),
    branchIdx: index('workflow_versions_branch_idx').on(table.workflowId, table.branchName),
    typeIdx: index('workflow_versions_type_idx').on(table.workflowId, table.versionType),
    hashIdx: index('workflow_versions_hash_idx').on(table.stateHash),
    uniqueVersionConstraint: uniqueIndex('workflow_versions_unique_version_idx').on(
      table.workflowId,
      table.versionNumber
    ),
    uniqueCurrentConstraint: uniqueIndex('workflow_versions_unique_current_idx').on(
      table.workflowId
    ),
  })
)

export const workflowVersionChanges = pgTable(
  'workflow_version_changes',
  {
    id: text('id').primaryKey(),
    versionId: text('version_id')
      .notNull()
      .references(() => workflowVersions.id, { onDelete: 'cascade' }),

    // Change classification
    changeType: text('change_type').notNull(), // 'block_added', 'block_removed', 'block_modified', etc.

    // Entity identification
    entityType: text('entity_type').notNull(), // 'block', 'edge', 'loop', 'parallel', 'metadata', 'variable'
    entityId: text('entity_id').notNull(),
    entityName: text('entity_name'), // Human-readable entity name for UI display

    // Change data
    oldData: jsonb('old_data'),
    newData: jsonb('new_data'),
    changeDescription: text('change_description'),

    // Change impact assessment
    impactLevel: text('impact_level'), // 'low', 'medium', 'high', 'critical'
    breakingChange: boolean('breaking_change').default(false),

    // Timestamps
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (table) => ({
    versionIdIdx: index('version_changes_version_id_idx').on(table.versionId),
    typeIdx: index('version_changes_type_idx').on(table.versionId, table.changeType),
    entityIdx: index('version_changes_entity_idx').on(
      table.versionId,
      table.entityType,
      table.entityId
    ),
    impactIdx: index('version_changes_impact_idx').on(table.versionId, table.impactLevel),
    breakingIdx: index('version_changes_breaking_idx').on(table.versionId, table.breakingChange),
  })
)

export const workflowVersionActivity = pgTable(
  'workflow_version_activity',
  {
    id: text('id').primaryKey(),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),
    versionId: text('version_id').references(() => workflowVersions.id, { onDelete: 'cascade' }),

    // Activity details
    activityType: text('activity_type').notNull(), // 'version_created', 'version_restored', etc.
    activityDescription: text('activity_description').notNull(),
    activityDetails: jsonb('activity_details').default('{}'),

    // User context
    userId: text('user_id').references(() => user.id),
    userAgent: text('user_agent'),
    ipAddress: text('ip_address'),

    // Related entities
    relatedVersionId: text('related_version_id').references(() => workflowVersions.id),
    relatedEntityType: text('related_entity_type'),
    relatedEntityId: text('related_entity_id'),

    // Timestamps
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (table) => ({
    workflowIdIdx: index('version_activity_workflow_id_idx').on(
      table.workflowId,
      table.createdAt.desc()
    ),
    versionIdIdx: index('version_activity_version_id_idx').on(
      table.versionId,
      table.createdAt.desc()
    ),
    userIdIdx: index('version_activity_user_id_idx').on(table.userId, table.createdAt.desc()),
    typeIdx: index('version_activity_type_idx').on(table.workflowId, table.activityType),
  })
)

export const workflowVersionConflicts = pgTable(
  'workflow_version_conflicts',
  {
    id: text('id').primaryKey(),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),
    sourceVersionId: text('source_version_id')
      .notNull()
      .references(() => workflowVersions.id),
    targetVersionId: text('target_version_id')
      .notNull()
      .references(() => workflowVersions.id),

    // Conflict details
    conflictType: text('conflict_type').notNull(), // 'block_conflict', 'edge_conflict', etc.
    entityPath: text('entity_path').notNull(), // JSON path to conflicting entity
    conflictDescription: text('conflict_description'),

    // Resolution data
    resolutionStrategy: text('resolution_strategy'), // 'use_source', 'use_target', 'merge_auto', etc.
    resolutionData: jsonb('resolution_data'),
    resolvedByUserId: text('resolved_by_user_id').references(() => user.id),
    resolvedAt: timestamp('resolved_at'),

    // Status
    status: text('status').default('unresolved'), // 'unresolved', 'resolved', 'deferred'

    // Timestamps
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    workflowIdx: index('version_conflicts_workflow_idx').on(table.workflowId, table.status),
    sourceIdx: index('version_conflicts_source_idx').on(table.sourceVersionId),
    targetIdx: index('version_conflicts_target_idx').on(table.targetVersionId),
    statusIdx: index('version_conflicts_status_idx').on(table.status, table.createdAt.desc()),
  })
)

export const workflowVersionTags = pgTable(
  'workflow_version_tags',
  {
    id: text('id').primaryKey(),
    versionId: text('version_id')
      .notNull()
      .references(() => workflowVersions.id, { onDelete: 'cascade' }),

    // Tag details
    tagName: text('tag_name').notNull(),
    tagColor: text('tag_color').default('#6B7280'),
    tagDescription: text('tag_description'),

    // Tag metadata
    isSystemTag: boolean('is_system_tag').default(false),
    tagOrder: integer('tag_order').default(0),

    // Audit
    createdByUserId: text('created_by_user_id').references(() => user.id),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (table) => ({
    versionIdIdx: index('version_tags_version_id_idx').on(table.versionId),
    nameIdx: index('version_tags_name_idx').on(table.tagName),
    systemIdx: index('version_tags_system_idx').on(table.isSystemTag),
    uniqueVersionTagConstraint: uniqueIndex('version_tags_version_tag_unique_idx').on(
      table.versionId,
      table.tagName
    ),
  })
)

export const workflowVersionStats = pgTable(
  'workflow_version_stats',
  {
    id: text('id').primaryKey(),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),
    versionId: text('version_id').references(() => workflowVersions.id, { onDelete: 'cascade' }),

    // Version statistics
    totalVersions: integer('total_versions').default(0),
    totalStorageBytes: integer('total_storage_bytes').default(0),
    avgVersionSizeBytes: integer('avg_version_size_bytes').default(0),

    // Change statistics
    totalChanges: integer('total_changes').default(0),
    breakingChanges: integer('breaking_changes').default(0),
    blocksAdded: integer('blocks_added').default(0),
    blocksRemoved: integer('blocks_removed').default(0),
    blocksModified: integer('blocks_modified').default(0),

    // Usage statistics
    restoreCount: integer('restore_count').default(0),
    comparisonCount: integer('comparison_count').default(0),
    downloadCount: integer('download_count').default(0),

    // Performance metrics
    avgCreationTimeMs: integer('avg_creation_time_ms').default(0),
    avgRestoreTimeMs: integer('avg_restore_time_ms').default(0),

    // Time windows
    statsPeriod: text('stats_period').default('all_time'), // 'all_time', 'last_30_days', 'last_7_days'
    calculatedAt: timestamp('calculated_at').notNull().defaultNow(),
  },
  (table) => ({
    workflowIdx: index('version_stats_workflow_idx').on(table.workflowId, table.statsPeriod),
    calculatedIdx: index('version_stats_calculated_idx').on(table.calculatedAt.desc()),
    uniqueStatsConstraint: uniqueIndex('version_stats_unique_idx').on(
      table.workflowId,
      table.versionId,
      table.statsPeriod
    ),
  })
)

// ========================
// COLLABORATIVE EDITING TABLES
// ========================

export const workflowCollaborationSessions = pgTable(
  'workflow_collaboration_sessions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    socketId: text('socket_id').notNull(),
    joinedAt: timestamp('joined_at').notNull().defaultNow(),
    lastActivity: timestamp('last_activity').notNull().defaultNow(),
    permissions: text('permissions').notNull().default('edit'), // 'view', 'edit', 'admin'
    userAgent: text('user_agent'),
    ipAddress: text('ip_address'),
  },
  (table) => ({
    workflowIdIdx: index('collaboration_sessions_workflow_id_idx').on(table.workflowId),
    userIdIdx: index('collaboration_sessions_user_id_idx').on(table.userId),
    socketIdIdx: index('collaboration_sessions_socket_id_idx').on(table.socketId),
    lastActivityIdx: index('collaboration_sessions_last_activity_idx').on(table.lastActivity),
    uniqueUserWorkflowSocketConstraint: uniqueIndex('collaboration_sessions_unique_idx').on(
      table.workflowId,
      table.userId,
      table.socketId
    ),
  })
)

export const workflowElementLocks = pgTable(
  'workflow_element_locks',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),
    elementType: text('element_type').notNull(), // 'block', 'edge', 'subblock', 'variable'
    elementId: text('element_id').notNull(),
    lockedByUserId: text('locked_by_user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    lockedAt: timestamp('locked_at').notNull().defaultNow(),
    expiresAt: timestamp('expires_at').notNull(),
    lockReason: text('lock_reason').default('editing'), // 'editing', 'reviewing', 'custom'
    metadata: jsonb('metadata').default('{}'),
  },
  (table) => ({
    workflowIdIdx: index('element_locks_workflow_id_idx').on(table.workflowId),
    userIdIdx: index('element_locks_user_id_idx').on(table.lockedByUserId),
    expiresAtIdx: index('element_locks_expires_at_idx').on(table.expiresAt),
    elementTypeIdIdx: index('element_locks_element_type_id_idx').on(
      table.elementType,
      table.elementId
    ),
    uniqueElementLockConstraint: uniqueIndex('element_locks_unique_idx').on(
      table.workflowId,
      table.elementType,
      table.elementId
    ),
  })
)

export const workflowComments: any = pgTable(
  'workflow_comments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),
    elementType: text('element_type').notNull(), // 'block', 'edge', 'workflow', 'variable'
    elementId: text('element_id'), // NULL for workflow-level comments
    authorId: text('author_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    content: text('content').notNull(),
    resolved: boolean('resolved').default(false),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
    parentCommentId: uuid('parent_comment_id').references(() => workflowComments.id, {
      onDelete: 'cascade',
    }),
    positionX: decimal('position_x', { precision: 10, scale: 2 }),
    positionY: decimal('position_y', { precision: 10, scale: 2 }),
    metadata: jsonb('metadata').default('{}'),
  },
  (table) => ({
    workflowIdIdx: index('workflow_comments_workflow_id_idx').on(table.workflowId),
    elementIdx: index('workflow_comments_element_idx').on(
      table.workflowId,
      table.elementType,
      table.elementId
    ),
    authorIdIdx: index('workflow_comments_author_id_idx').on(table.authorId),
    parentIdIdx: index('workflow_comments_parent_id_idx').on(table.parentCommentId),
    createdAtIdx: index('workflow_comments_created_at_idx').on(table.createdAt),
  })
)

export const workflowLiveOperations = pgTable(
  'workflow_live_operations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),
    operationType: text('operation_type').notNull(), // 'insert', 'delete', 'update', 'move'
    operationTarget: text('operation_target').notNull(), // 'block', 'edge', 'property', 'subblock'
    operationPayload: jsonb('operation_payload').notNull(),
    authorId: text('author_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    timestampMs: integer('timestamp_ms').notNull(), // Microsecond precision timestamp
    vectorClock: jsonb('vector_clock').default('{}'),
    applied: boolean('applied').default(false),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (table) => ({
    workflowIdIdx: index('live_operations_workflow_id_idx').on(table.workflowId),
    timestampIdx: index('live_operations_timestamp_idx').on(table.workflowId, table.timestampMs),
    authorIdIdx: index('live_operations_author_id_idx').on(table.authorId),
    appliedIdx: index('live_operations_applied_idx').on(table.applied),
  })
)

export const workflowCollaborators = pgTable(
  'workflow_collaborators',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workflowId: text('workflow_id')
      .notNull()
      .references(() => workflow.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    permissionLevel: text('permission_level').notNull().default('edit'), // 'view', 'edit', 'admin'
    addedByUserId: text('added_by_user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    addedAt: timestamp('added_at').notNull().defaultNow(),
    lastAccess: timestamp('last_access'),
  },
  (table) => ({
    workflowIdIdx: index('workflow_collaborators_workflow_id_idx').on(table.workflowId),
    userIdIdx: index('workflow_collaborators_user_id_idx').on(table.userId),
    addedByIdx: index('workflow_collaborators_added_by_idx').on(table.addedByUserId),
    uniqueCollaboratorConstraint: uniqueIndex('workflow_collaborators_unique_idx').on(
      table.workflowId,
      table.userId
    ),
  })
)

// Registry System Tables for Dynamic Tool and Block Registration

export const registryTools = pgTable(
  'registry_tools',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    workspaceId: text('workspace_id').references(() => workspace.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    displayName: text('display_name').notNull(),
    description: text('description'),
    icon: text('icon').default('tool-icon'),
    category: text('category').default('custom'),
    version: text('version').notNull().default('1.0.0'),
    status: text('status').notNull().default('active'), // active, inactive, error, pending_approval

    // Tool manifest and configuration
    manifest: jsonb('manifest').notNull().default('{}'),
    configSchema: jsonb('config_schema').notNull().default('{}'),
    inputSchema: jsonb('input_schema').notNull().default('{}'),
    outputSchema: jsonb('output_schema').notNull().default('{}'),

    // Webhook integration
    webhookUrl: text('webhook_url').notNull(),
    webhookMethod: text('webhook_method').notNull().default('POST'),
    webhookTimeout: integer('webhook_timeout').default(30000), // milliseconds
    webhookRetryCount: integer('webhook_retry_count').default(3),

    // Authentication configuration
    authentication: jsonb('authentication').default('{}'),
    apiKeyEncrypted: text('api_key_encrypted'), // Encrypted API key for the tool

    // Usage tracking
    usageCount: integer('usage_count').notNull().default(0),
    lastUsedAt: timestamp('last_used_at'),
    errorCount: integer('error_count').notNull().default(0),
    lastErrorAt: timestamp('last_error_at'),
    lastErrorMessage: text('last_error_message'),

    // Metadata
    tags: jsonb('tags').default('[]'),
    metadata: jsonb('metadata').default('{}'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    userIdIdx: index('registry_tools_user_id_idx').on(table.userId),
    workspaceIdIdx: index('registry_tools_workspace_id_idx').on(table.workspaceId),
    statusIdx: index('registry_tools_status_idx').on(table.status),
    categoryIdx: index('registry_tools_category_idx').on(table.category),
    usageIdx: index('registry_tools_usage_idx').on(table.usageCount, table.lastUsedAt),
    nameUserUnique: uniqueIndex('registry_tools_name_user_unique').on(table.name, table.userId),
  })
)

export const registryBlocks = pgTable(
  'registry_blocks',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    workspaceId: text('workspace_id').references(() => workspace.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    displayName: text('display_name').notNull(),
    description: text('description'),
    icon: text('icon').default('block-icon'),
    category: text('category').default('custom'),
    version: text('version').notNull().default('1.0.0'),
    status: text('status').notNull().default('active'), // active, inactive, error, pending_approval

    // Block manifest and configuration
    manifest: jsonb('manifest').notNull().default('{}'),
    inputPorts: jsonb('input_ports').notNull().default('[]'),
    outputPorts: jsonb('output_ports').notNull().default('[]'),
    configSchema: jsonb('config_schema').notNull().default('{}'),

    // Execution configuration
    executionUrl: text('execution_url').notNull(),
    validationUrl: text('validation_url'),
    executionTimeout: integer('execution_timeout').default(300000), // 5 minutes default

    // Usage tracking
    usageCount: integer('usage_count').notNull().default(0),
    lastUsedAt: timestamp('last_used_at'),
    errorCount: integer('error_count').notNull().default(0),
    lastErrorAt: timestamp('last_error_at'),
    lastErrorMessage: text('last_error_message'),

    // Metadata
    tags: jsonb('tags').default('[]'),
    metadata: jsonb('metadata').default('{}'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    userIdIdx: index('registry_blocks_user_id_idx').on(table.userId),
    workspaceIdIdx: index('registry_blocks_workspace_id_idx').on(table.workspaceId),
    statusIdx: index('registry_blocks_status_idx').on(table.status),
    categoryIdx: index('registry_blocks_category_idx').on(table.category),
    usageIdx: index('registry_blocks_usage_idx').on(table.usageCount, table.lastUsedAt),
    nameUserUnique: uniqueIndex('registry_blocks_name_user_unique').on(table.name, table.userId),
  })
)

export const webhookExecutionLogs = pgTable(
  'webhook_execution_logs',
  {
    id: text('id').primaryKey(),
    registryItemId: text('registry_item_id').notNull(), // References either registry_tools.id or registry_blocks.id
    registryType: text('registry_type').notNull(), // 'tool' or 'block'
    executionId: text('execution_id').notNull(),
    workflowId: text('workflow_id').references(() => workflow.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),

    // Request details
    webhookUrl: text('webhook_url').notNull(),
    requestMethod: text('request_method').notNull(),
    requestHeaders: jsonb('request_headers').default('{}'),
    requestBody: jsonb('request_body'),
    requestSignature: text('request_signature'), // HMAC signature for security validation

    // Response details
    responseStatus: integer('response_status'),
    responseHeaders: jsonb('response_headers').default('{}'),
    responseBody: jsonb('response_body'),
    responseTimeMs: integer('response_time_ms'),

    // Error handling
    errorMessage: text('error_message'),
    retryCount: integer('retry_count').default(0),
    isSuccessful: boolean('is_successful').notNull().default(false),

    // Timing
    startedAt: timestamp('started_at').notNull().defaultNow(),
    completedAt: timestamp('completed_at'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (table) => ({
    registryItemIdx: index('webhook_execution_logs_registry_item_idx').on(
      table.registryItemId,
      table.registryType
    ),
    executionIdIdx: index('webhook_execution_logs_execution_id_idx').on(table.executionId),
    workflowIdIdx: index('webhook_execution_logs_workflow_id_idx').on(table.workflowId),
    userIdIdx: index('webhook_execution_logs_user_id_idx').on(table.userId),
    startedAtIdx: index('webhook_execution_logs_started_at_idx').on(table.startedAt),
    successIdx: index('webhook_execution_logs_success_idx').on(table.isSuccessful, table.startedAt),
  })
)

export const registryApiKeys = pgTable(
  'registry_api_keys',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    keyHash: text('key_hash').notNull().unique(), // Hashed API key
    permissions: jsonb('permissions').notNull().default('["read"]'), // ["read", "write", "admin"]
    rateLimit: integer('rate_limit').default(100), // requests per minute
    lastUsedAt: timestamp('last_used_at'),
    usageCount: integer('usage_count').notNull().default(0),
    isActive: boolean('is_active').notNull().default(true),
    expiresAt: timestamp('expires_at'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    userIdIdx: index('registry_api_keys_user_id_idx').on(table.userId),
    activeIdx: index('registry_api_keys_active_idx').on(table.isActive, table.expiresAt),
  })
)

export const registryRateLimits = pgTable('registry_rate_limits', {
  userId: text('user_id')
    .primaryKey()
    .references(() => user.id, { onDelete: 'cascade' }),
  toolRegistrations: integer('tool_registrations').notNull().default(0),
  blockRegistrations: integer('block_registrations').notNull().default(0),
  webhookCalls: integer('webhook_calls').notNull().default(0),
  windowStart: timestamp('window_start').notNull().defaultNow(),
  lastRequestAt: timestamp('last_request_at').notNull().defaultNow(),
  isRateLimited: boolean('is_rate_limited').notNull().default(false),
  rateLimitResetAt: timestamp('rate_limit_reset_at'),
})
