import { ComponentIcon } from '@/components/icons'
import type { BlockConfig } from '@/blocks/types'
import type { AuthResponse } from '@/tools/auth/types'

export const AuthManagerBlock: BlockConfig<AuthResponse> = {
  type: 'auth_manager',
  name: 'Auth Manager',
  description: 'Centralized authentication and token management',
  longDescription:
    'Manage authentication tokens, API keys, and OAuth flows with automatic token refresh, secure storage, and expiration handling. Supports multiple authentication standards.',
  docsLink: 'https://docs.sim.ai/blocks/auth-manager',
  category: 'blocks',
  bgColor: '#DC2626',
  icon: ComponentIcon,
  subBlocks: [
    {
      id: 'authType',
      title: 'Authentication Type',
      type: 'dropdown',
      layout: 'full',
      required: true,
      options: [
        { label: 'OAuth 2.0 Authorization Code', id: 'oauth2_code' },
        { label: 'OAuth 2.0 Client Credentials', id: 'oauth2_client' },
        { label: 'OAuth 2.0 Password Grant', id: 'oauth2_password' },
        { label: 'JWT Token Refresh', id: 'jwt_refresh' },
        { label: 'API Key Management', id: 'api_key' },
        { label: 'Basic Auth Credentials', id: 'basic_auth' },
        { label: 'Custom Authentication', id: 'custom' },
      ],
    },
    {
      id: 'tokenEndpoint',
      title: 'Token Endpoint',
      type: 'long-input',
      layout: 'full',
      placeholder: 'https://auth.example.com/oauth/token',
      condition: {
        field: 'authType',
        value: ['oauth2_code', 'oauth2_client', 'oauth2_password', 'jwt_refresh'],
      },
      required: true,
    },
    {
      id: 'clientId',
      title: 'Client ID',
      type: 'short-input',
      layout: 'half',
      placeholder: 'your-client-id',
      condition: {
        field: 'authType',
        value: ['oauth2_code', 'oauth2_client', 'oauth2_password'],
      },
      required: true,
    },
    {
      id: 'clientSecret',
      title: 'Client Secret',
      type: 'short-input',
      layout: 'half',
      placeholder: 'your-client-secret',
      password: true,
      condition: {
        field: 'authType',
        value: ['oauth2_code', 'oauth2_client', 'oauth2_password'],
      },
      required: true,
    },
    {
      id: 'username',
      title: 'Username',
      type: 'short-input',
      layout: 'half',
      placeholder: 'username',
      condition: { field: 'authType', value: ['oauth2_password', 'basic_auth'] },
      required: true,
    },
    {
      id: 'password',
      title: 'Password',
      type: 'short-input',
      layout: 'half',
      placeholder: 'password',
      password: true,
      condition: { field: 'authType', value: ['oauth2_password', 'basic_auth'] },
      required: true,
    },
    {
      id: 'authorizationCode',
      title: 'Authorization Code',
      type: 'short-input',
      layout: 'full',
      placeholder: 'authorization-code-from-callback',
      condition: { field: 'authType', value: 'oauth2_code' },
      required: true,
      description: 'Code received from authorization callback',
    },
    {
      id: 'redirectUri',
      title: 'Redirect URI',
      type: 'short-input',
      layout: 'full',
      placeholder: 'https://your-app.com/callback',
      condition: { field: 'authType', value: 'oauth2_code' },
      required: true,
    },
    {
      id: 'scope',
      title: 'Requested Scopes',
      type: 'short-input',
      layout: 'full',
      placeholder: 'read:user read:repo write:repo',
      condition: {
        field: 'authType',
        value: ['oauth2_code', 'oauth2_client', 'oauth2_password'],
      },
      description: 'Space-separated list of OAuth scopes',
    },
    {
      id: 'currentToken',
      title: 'Current Token',
      type: 'short-input',
      layout: 'full',
      placeholder: 'current-jwt-token',
      password: true,
      condition: { field: 'authType', value: 'jwt_refresh' },
      required: true,
    },
    {
      id: 'refreshToken',
      title: 'Refresh Token',
      type: 'short-input',
      layout: 'full',
      placeholder: 'refresh-token',
      password: true,
      condition: { field: 'authType', value: 'jwt_refresh' },
      required: true,
    },
    {
      id: 'apiKey',
      title: 'API Key',
      type: 'short-input',
      layout: 'half',
      placeholder: 'your-api-key',
      password: true,
      condition: { field: 'authType', value: 'api_key' },
      required: true,
    },
    {
      id: 'apiKeyLocation',
      title: 'API Key Location',
      type: 'dropdown',
      layout: 'half',
      condition: { field: 'authType', value: 'api_key' },
      options: [
        { label: 'Header', id: 'header' },
        { label: 'Query Parameter', id: 'query' },
        { label: 'Request Body', id: 'body' },
      ],
      value: () => 'header',
    },
    {
      id: 'apiKeyName',
      title: 'API Key Header/Parameter Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'X-API-Key',
      condition: { field: 'authType', value: 'api_key' },
      value: () => 'X-API-Key',
    },
    {
      id: 'customEndpoint',
      title: 'Authentication Endpoint',
      type: 'long-input',
      layout: 'full',
      placeholder: 'https://api.example.com/auth/login',
      condition: { field: 'authType', value: 'custom' },
      required: true,
    },
    {
      id: 'customMethod',
      title: 'HTTP Method',
      type: 'dropdown',
      layout: 'half',
      condition: { field: 'authType', value: 'custom' },
      options: [
        { label: 'POST', id: 'POST' },
        { label: 'GET', id: 'GET' },
        { label: 'PUT', id: 'PUT' },
      ],
      value: () => 'POST',
    },
    {
      id: 'customHeaders',
      title: 'Custom Headers',
      type: 'table',
      layout: 'full',
      columns: ['Key', 'Value'],
      condition: { field: 'authType', value: 'custom' },
    },
    {
      id: 'customPayload',
      title: 'Authentication Payload',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: `{
  "username": "<username>",
  "password": "<password>",
  "grant_type": "password"
}`,
      condition: { field: 'authType', value: 'custom' },
      description: 'JSON payload for custom authentication',
    },
    {
      id: 'tokenExpiry',
      title: 'Token Expiry Handling',
      type: 'dropdown',
      layout: 'half',
      options: [
        { label: 'Auto Refresh', id: 'auto_refresh' },
        { label: 'Manual Refresh', id: 'manual' },
        { label: 'No Expiry', id: 'none' },
      ],
      value: () => 'auto_refresh',
      description: 'How to handle token expiration',
    },
    {
      id: 'refreshBuffer',
      title: 'Refresh Buffer (minutes)',
      type: 'slider',
      layout: 'half',
      min: 1,
      max: 60,
      step: 1,
      value: () => '5',
      condition: { field: 'tokenExpiry', value: 'auto_refresh' },
      description: 'Refresh token this many minutes before expiry',
    },
    {
      id: 'secureStorage',
      title: 'Use Secure Storage',
      type: 'switch',
      layout: 'half',
      description: 'Store tokens securely with encryption',
      value: () => true,
    },
    {
      id: 'tokenValidation',
      title: 'Enable Token Validation',
      type: 'switch',
      layout: 'half',
      description: 'Validate token format and expiry before use',
      value: () => true,
    },
  ],
  tools: {
    access: ['auth_manager'],
  },
  inputs: {
    authType: { type: 'string', description: 'Type of authentication' },
    tokenEndpoint: { type: 'string', description: 'Token endpoint URL' },
    clientId: { type: 'string', description: 'OAuth client ID' },
    clientSecret: { type: 'string', description: 'OAuth client secret' },
    username: { type: 'string', description: 'Username for authentication' },
    password: { type: 'string', description: 'Password for authentication' },
    authorizationCode: { type: 'string', description: 'OAuth authorization code' },
    redirectUri: { type: 'string', description: 'OAuth redirect URI' },
    scope: { type: 'string', description: 'OAuth scopes' },
    currentToken: { type: 'string', description: 'Current JWT token' },
    refreshToken: { type: 'string', description: 'Refresh token' },
    apiKey: { type: 'string', description: 'API key' },
    apiKeyLocation: { type: 'string', description: 'Where to place API key' },
    apiKeyName: { type: 'string', description: 'API key parameter name' },
    customEndpoint: { type: 'string', description: 'Custom auth endpoint' },
    customMethod: { type: 'string', description: 'Custom auth HTTP method' },
    customHeaders: { type: 'json', description: 'Custom auth headers' },
    customPayload: { type: 'json', description: 'Custom auth payload' },
    tokenExpiry: { type: 'string', description: 'Token expiry handling' },
    refreshBuffer: { type: 'number', description: 'Token refresh buffer minutes' },
    secureStorage: { type: 'boolean', description: 'Use secure token storage' },
    tokenValidation: { type: 'boolean', description: 'Enable token validation' },
  },
  outputs: {
    accessToken: { type: 'string', description: 'Valid access token' },
    tokenType: { type: 'string', description: 'Token type (Bearer, etc.)' },
    expiresIn: { type: 'number', description: 'Token expiry in seconds' },
    expiresAt: { type: 'string', description: 'Token expiry timestamp' },
    refreshToken: { type: 'string', description: 'Refresh token if available' },
    scopes: { type: 'array', description: 'Granted scopes' },
    authHeader: { type: 'string', description: 'Complete authorization header' },
    isValid: { type: 'boolean', description: 'Whether token is currently valid' },
    metadata: { type: 'json', description: 'Additional authentication metadata' },
    error: { type: 'string', description: 'Error message if authentication failed' },
  },
}
