import { DocumentIcon } from '@heroicons/react/24/outline'
import type { BlockConfig } from '@/blocks/types'
import type { FileResponse } from '@/tools/file/types'

export const FileProcessorBlock: BlockConfig<FileResponse> = {
  type: 'file_processor',
  name: 'File Processor',
  description: 'Advanced file processing with format conversion and data extraction',
  longDescription:
    'Process various file formats including CSV, Excel, PDF, Word, images, and more. Extract data, convert formats, validate content, and perform batch operations with comprehensive error handling.',
  docsLink: 'https://docs.sim.ai/blocks/file-processor',
  category: 'blocks',
  bgColor: '#F59E0B',
  icon: DocumentIcon,
  subBlocks: [
    {
      id: 'inputSource',
      title: 'Input Source',
      type: 'dropdown',
      layout: 'half',
      required: true,
      options: [
        { label: 'File Upload', id: 'upload' },
        { label: 'URL Download', id: 'url' },
        { label: 'Cloud Storage', id: 'cloud' },
        { label: 'Previous Block Output', id: 'reference' },
        { label: 'Base64 Content', id: 'base64' },
      ],
      value: () => 'upload',
    },
    {
      id: 'processingMode',
      title: 'Processing Mode',
      type: 'dropdown',
      layout: 'half',
      required: true,
      options: [
        { label: 'Single File', id: 'single' },
        { label: 'Batch Processing', id: 'batch' },
        { label: 'ZIP Archive', id: 'zip' },
        { label: 'Directory Processing', id: 'directory' },
      ],
      value: () => 'single',
    },
    {
      id: 'fileUpload',
      title: 'Upload File',
      type: 'file-upload',
      layout: 'full',
      condition: { field: 'inputSource', value: 'upload' },
      acceptedTypes: '.csv,.xlsx,.xls,.pdf,.docx,.doc,.txt,.json,.xml,.html,.png,.jpg,.jpeg,.gif,.zip',
      multiple: true,
      maxSize: 50,
      required: true,
      description: 'Upload files to process (max 50MB each)',
    },
    {
      id: 'fileUrl',
      title: 'File URL',
      type: 'long-input',
      layout: 'full',
      placeholder: 'https://example.com/data/file.csv',
      condition: { field: 'inputSource', value: 'url' },
      required: true,
      rows: 2,
      description: 'URL to download file from',
    },
    {
      id: 'cloudProvider',
      title: 'Cloud Provider',
      type: 'dropdown',
      layout: 'half',
      condition: { field: 'inputSource', value: 'cloud' },
      options: [
        { label: 'Amazon S3', id: 's3' },
        { label: 'Google Drive', id: 'gdrive' },
        { label: 'Dropbox', id: 'dropbox' },
        { label: 'OneDrive', id: 'onedrive' },
        { label: 'Google Cloud Storage', id: 'gcs' },
      ],
      required: true,
    },
    {
      id: 'cloudPath',
      title: 'Cloud File Path',
      type: 'short-input',
      layout: 'half',
      placeholder: 'bucket/folder/file.csv',
      condition: { field: 'inputSource', value: 'cloud' },
      required: true,
    },
    {
      id: 'fileReference',
      title: 'File Reference',
      type: 'short-input',
      layout: 'full',
      placeholder: '<previous.block.fileUrl>',
      condition: { field: 'inputSource', value: 'reference' },
      required: true,
      description: 'Reference to file from previous block output',
    },
    {
      id: 'base64Content',
      title: 'Base64 File Content',
      type: 'code',
      layout: 'full',
      language: 'text',
      placeholder: 'data:application/pdf;base64,JVBERi0xLjQKMSAwIG9iag...',
      condition: { field: 'inputSource', value: 'base64' },
      required: true,
      rows: 6,
      description: 'Base64 encoded file content with data URI',
    },
    {
      id: 'operation',
      title: 'File Operation',
      type: 'dropdown',
      layout: 'full',
      required: true,
      options: [
        { label: 'Extract Data', id: 'extract' },
        { label: 'Convert Format', id: 'convert' },
        { label: 'Validate Content', id: 'validate' },
        { label: 'Split/Merge', id: 'split_merge' },
        { label: 'OCR Text Recognition', id: 'ocr' },
        { label: 'Metadata Extraction', id: 'metadata' },
        { label: 'Content Analysis', id: 'analysis' },
        { label: 'Compression/Decompression', id: 'compression' },
      ],
      value: () => 'extract',
    },
    // Extract Data Configuration
    {
      id: 'extractionType',
      title: 'Extraction Type',
      type: 'dropdown',
      layout: 'half',
      condition: { field: 'operation', value: 'extract' },
      options: [
        { label: 'Structured Data (CSV/Excel)', id: 'structured' },
        { label: 'Text Content', id: 'text' },
        { label: 'Images', id: 'images' },
        { label: 'Tables', id: 'tables' },
        { label: 'Form Data', id: 'forms' },
        { label: 'Custom Pattern', id: 'pattern' },
      ],
      required: true,
    },
    {
      id: 'dataFormat',
      title: 'Output Data Format',
      type: 'dropdown',
      layout: 'half',
      condition: { field: 'operation', value: 'extract' },
      options: [
        { label: 'JSON', id: 'json' },
        { label: 'CSV', id: 'csv' },
        { label: 'Excel', id: 'excel' },
        { label: 'XML', id: 'xml' },
        { label: 'Plain Text', id: 'text' },
      ],
      value: () => 'json',
    },
    {
      id: 'csvConfig',
      title: 'CSV Configuration',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: `{
  "delimiter": ",",
  "quoteChar": "\\"",
  "escapeChar": "\\\\",
  "hasHeader": true,
  "skipRows": 0,
  "encoding": "utf-8",
  "dateFormat": "YYYY-MM-DD"
}`,
      condition: { 
        field: 'extractionType', 
        value: 'structured',
      },
      description: 'CSV parsing configuration',
    },
    {
      id: 'excelConfig',
      title: 'Excel Configuration',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: `{
  "sheetName": "Sheet1",
  "sheetIndex": 0,
  "hasHeader": true,
  "skipRows": 0,
  "maxRows": 0,
  "columns": ["A", "B", "C", "D"],
  "dateColumns": ["created_date", "updated_date"]
}`,
      condition: { 
        field: 'extractionType', 
        value: 'structured',
      },
      description: 'Excel parsing configuration',
    },
    {
      id: 'extractionPattern',
      title: 'Extraction Pattern',
      type: 'code',
      layout: 'full',
      language: 'javascript',
      placeholder: `// Regular expression pattern for custom extraction
const patterns = {
  email: /([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,})/g,
  phone: /\\b\\d{3}-\\d{3}-\\d{4}\\b/g,
  date: /\\b\\d{1,2}\/\\d{1,2}\/\\d{4}\\b/g,
  currency: /\\$([0-9,]+\\.?[0-9]*)/g
};

// Return object with extraction logic
{
  patterns: patterns,
  fields: ['email', 'phone', 'date', 'currency']
}`,
      condition: { field: 'extractionType', value: 'pattern' },
      required: true,
      rows: 12,
      description: 'Custom extraction patterns and logic',
    },
    // Format Conversion Configuration
    {
      id: 'targetFormat',
      title: 'Target Format',
      type: 'dropdown',
      layout: 'half',
      condition: { field: 'operation', value: 'convert' },
      options: [
        { label: 'PDF', id: 'pdf' },
        { label: 'Excel (.xlsx)', id: 'xlsx' },
        { label: 'CSV', id: 'csv' },
        { label: 'JSON', id: 'json' },
        { label: 'XML', id: 'xml' },
        { label: 'HTML', id: 'html' },
        { label: 'Plain Text', id: 'txt' },
        { label: 'Image (PNG/JPG)', id: 'image' },
      ],
      required: true,
    },
    {
      id: 'conversionOptions',
      title: 'Conversion Options',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: `{
  "quality": "high",
  "preserveFormatting": true,
  "includeImages": true,
  "pageRange": "all",
  "compression": "medium",
  "colorSpace": "RGB",
  "dpi": 300
}`,
      condition: { field: 'operation', value: 'convert' },
      description: 'Conversion-specific options',
    },
    // Validation Configuration
    {
      id: 'validationType',
      title: 'Validation Type',
      type: 'dropdown',
      layout: 'half',
      condition: { field: 'operation', value: 'validate' },
      options: [
        { label: 'File Format', id: 'format' },
        { label: 'Data Schema', id: 'schema' },
        { label: 'Content Rules', id: 'rules' },
        { label: 'Virus Scan', id: 'security' },
        { label: 'Integrity Check', id: 'integrity' },
      ],
      required: true,
    },
    {
      id: 'validationSchema',
      title: 'Validation Schema',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: `{
  "type": "object",
  "required": ["name", "email", "age"],
  "properties": {
    "name": {"type": "string", "minLength": 1},
    "email": {"type": "string", "format": "email"},
    "age": {"type": "number", "minimum": 0, "maximum": 120}
  },
  "additionalProperties": false
}`,
      condition: { field: 'validationType', value: 'schema' },
      description: 'JSON Schema for data validation',
    },
    {
      id: 'validationRules',
      title: 'Validation Rules',
      type: 'table',
      layout: 'full',
      columns: ['Field', 'Rule Type', 'Rule Value', 'Error Message'],
      condition: { field: 'validationType', value: 'rules' },
      description: 'Custom validation rules',
    },
    // OCR Configuration
    {
      id: 'ocrLanguage',
      title: 'OCR Language',
      type: 'dropdown',
      layout: 'half',
      condition: { field: 'operation', value: 'ocr' },
      options: [
        { label: 'English', id: 'en' },
        { label: 'Spanish', id: 'es' },
        { label: 'French', id: 'fr' },
        { label: 'German', id: 'de' },
        { label: 'Chinese', id: 'zh' },
        { label: 'Japanese', id: 'ja' },
        { label: 'Auto-detect', id: 'auto' },
      ],
      value: () => 'en',
    },
    {
      id: 'ocrOptions',
      title: 'OCR Options',
      type: 'checkbox-list',
      layout: 'full',
      condition: { field: 'operation', value: 'ocr' },
      options: [
        { label: 'Preserve Layout', id: 'preserve_layout' },
        { label: 'Extract Tables', id: 'extract_tables' },
        { label: 'Recognize Handwriting', id: 'handwriting' },
        { label: 'Confidence Scoring', id: 'confidence' },
        { label: 'Word Boundaries', id: 'word_boundaries' },
      ],
      value: () => ['preserve_layout', 'confidence'],
      description: 'OCR processing options',
    },
    // Batch Processing Configuration
    {
      id: 'batchSize',
      title: 'Batch Size',
      type: 'slider',
      layout: 'half',
      min: 1,
      max: 100,
      step: 1,
      value: () => '10',
      condition: { field: 'processingMode', value: 'batch' },
      description: 'Number of files to process in parallel',
    },
    {
      id: 'failureHandling',
      title: 'Failure Handling',
      type: 'dropdown',
      layout: 'half',
      options: [
        { label: 'Stop on First Error', id: 'stop' },
        { label: 'Continue Processing', id: 'continue' },
        { label: 'Retry Failed Files', id: 'retry' },
        { label: 'Skip Invalid Files', id: 'skip' },
      ],
      value: () => 'continue',
      description: 'How to handle processing failures',
    },
    {
      id: 'outputNaming',
      title: 'Output File Naming',
      type: 'short-input',
      layout: 'full',
      placeholder: 'processed_{{originalName}}_{{timestamp}}',
      description: 'Naming pattern for output files (supports variables)',
    },
    {
      id: 'outputDestination',
      title: 'Output Destination',
      type: 'dropdown',
      layout: 'half',
      options: [
        { label: 'Return Data', id: 'return' },
        { label: 'Save to Cloud Storage', id: 'cloud' },
        { label: 'Download URL', id: 'url' },
        { label: 'Email Attachment', id: 'email' },
      ],
      value: () => 'return',
      description: 'Where to store processed files',
    },
    {
      id: 'compressionLevel',
      title: 'Compression Level',
      type: 'dropdown',
      layout: 'half',
      condition: { field: 'operation', value: 'compression' },
      options: [
        { label: 'None', id: 'none' },
        { label: 'Fast', id: 'fast' },
        { label: 'Balanced', id: 'balanced' },
        { label: 'Maximum', id: 'maximum' },
      ],
      value: () => 'balanced',
      description: 'Compression level for output',
    },
    {
      id: 'processingTimeout',
      title: 'Processing Timeout (seconds)',
      type: 'slider',
      layout: 'full',
      min: 30,
      max: 3600,
      step: 30,
      value: () => '300',
      description: 'Maximum time to wait for processing completion',
    },
  ],
  tools: {
    access: ['file_processor'],
  },
  inputs: {
    inputSource: { type: 'string', description: 'Source of input files' },
    processingMode: { type: 'string', description: 'File processing mode' },
    fileUpload: { type: 'string', description: 'Uploaded file data' },
    fileUrl: { type: 'string', description: 'URL to download file from' },
    cloudProvider: { type: 'string', description: 'Cloud storage provider' },
    cloudPath: { type: 'string', description: 'Path to file in cloud storage' },
    fileReference: { type: 'string', description: 'Reference to file from previous block' },
    base64Content: { type: 'string', description: 'Base64 encoded file content' },
    operation: { type: 'string', description: 'File processing operation' },
    extractionType: { type: 'string', description: 'Type of data extraction' },
    dataFormat: { type: 'string', description: 'Output data format' },
    csvConfig: { type: 'json', description: 'CSV parsing configuration' },
    excelConfig: { type: 'json', description: 'Excel parsing configuration' },
    extractionPattern: { type: 'string', description: 'Custom extraction patterns' },
    targetFormat: { type: 'string', description: 'Target file format for conversion' },
    conversionOptions: { type: 'json', description: 'Format conversion options' },
    validationType: { type: 'string', description: 'Type of file validation' },
    validationSchema: { type: 'json', description: 'JSON schema for validation' },
    validationRules: { type: 'json', description: 'Custom validation rules' },
    ocrLanguage: { type: 'string', description: 'OCR recognition language' },
    ocrOptions: { type: 'json', description: 'OCR processing options' },
    batchSize: { type: 'number', description: 'Batch processing size' },
    failureHandling: { type: 'string', description: 'Failure handling strategy' },
    outputNaming: { type: 'string', description: 'Output file naming pattern' },
    outputDestination: { type: 'string', description: 'Output destination type' },
    compressionLevel: { type: 'string', description: 'File compression level' },
    processingTimeout: { type: 'number', description: 'Processing timeout in seconds' },
  },
  outputs: {
    processedData: { type: 'json', description: 'Extracted or processed data' },
    processedFiles: { type: 'array', description: 'List of processed files' },
    fileCount: { type: 'number', description: 'Number of files processed' },
    successCount: { type: 'number', description: 'Successfully processed files' },
    errorCount: { type: 'number', description: 'Files with processing errors' },
    errors: { type: 'array', description: 'Processing errors and details' },
    validationResults: { type: 'json', description: 'File validation results' },
    ocrResults: { type: 'json', description: 'OCR text recognition results' },
    metadata: { type: 'json', description: 'Extracted file metadata' },
    compressionRatio: { type: 'number', description: 'Achieved compression ratio' },
    processingTime: { type: 'number', description: 'Total processing time in milliseconds' },
    downloadUrls: { type: 'array', description: 'URLs to download processed files' },
    storageInfo: { type: 'json', description: 'Cloud storage information' },
    statistics: { type: 'json', description: 'Processing statistics and metrics' },
    error: { type: 'string', description: 'Error message if processing failed' },
  },
}