import { DatabaseIcon } from '@/components/icons'
import type { BlockConfig } from '@/blocks/types'
import type { DatabaseResponse } from '@/tools/database/types'

export const SqlQueryBuilderBlock: BlockConfig<DatabaseResponse> = {
  type: 'sql_query_builder',
  name: 'SQL Query Builder',
  description: 'Visual SQL query builder with advanced database operations',
  longDescription:
    'Build complex SQL queries visually with support for joins, subqueries, aggregations, and advanced database operations. Includes connection pooling, transaction management, and query optimization.',
  docsLink: 'https://docs.sim.ai/blocks/sql-query-builder',
  category: 'blocks',
  bgColor: '#1F2937',
  icon: DatabaseIcon,
  subBlocks: [
    {
      id: 'databaseType',
      title: 'Database Type',
      type: 'dropdown',
      layout: 'half',
      required: true,
      options: [
        { label: 'PostgreSQL', id: 'postgresql' },
        { label: 'MySQL', id: 'mysql' },
        { label: 'SQLite', id: 'sqlite' },
        { label: 'SQL Server', id: 'sqlserver' },
        { label: 'Oracle', id: 'oracle' },
        { label: 'MariaDB', id: 'mariadb' },
      ],
    },
    {
      id: 'connectionString',
      title: 'Connection String',
      type: 'long-input',
      layout: 'full',
      placeholder: 'postgresql://username:password@localhost:5432/database',
      password: true,
      required: true,
      rows: 2,
      description: 'Database connection string or use individual fields below',
    },
    {
      id: 'useIndividualFields',
      title: 'Use Individual Connection Fields',
      type: 'switch',
      layout: 'full',
      description: 'Use separate fields instead of connection string',
    },
    {
      id: 'host',
      title: 'Host',
      type: 'short-input',
      layout: 'half',
      placeholder: 'localhost',
      condition: { field: 'useIndividualFields', value: true },
      required: true,
    },
    {
      id: 'port',
      title: 'Port',
      type: 'short-input',
      layout: 'half',
      placeholder: '5432',
      condition: { field: 'useIndividualFields', value: true },
      required: true,
    },
    {
      id: 'database',
      title: 'Database Name',
      type: 'short-input',
      layout: 'half',
      placeholder: 'mydb',
      condition: { field: 'useIndividualFields', value: true },
      required: true,
    },
    {
      id: 'username',
      title: 'Username',
      type: 'short-input',
      layout: 'half',
      placeholder: 'username',
      condition: { field: 'useIndividualFields', value: true },
      required: true,
    },
    {
      id: 'password',
      title: 'Password',
      type: 'short-input',
      layout: 'full',
      placeholder: 'password',
      password: true,
      condition: { field: 'useIndividualFields', value: true },
      required: true,
    },
    {
      id: 'queryMode',
      title: 'Query Mode',
      type: 'dropdown',
      layout: 'half',
      required: true,
      options: [
        { label: 'Visual Builder', id: 'visual' },
        { label: 'Raw SQL', id: 'raw' },
        { label: 'Template Query', id: 'template' },
      ],
      value: () => 'visual',
    },
    {
      id: 'operation',
      title: 'Operation Type',
      type: 'dropdown',
      layout: 'half',
      condition: { field: 'queryMode', value: 'visual' },
      options: [
        { label: 'SELECT', id: 'select' },
        { label: 'INSERT', id: 'insert' },
        { label: 'UPDATE', id: 'update' },
        { label: 'DELETE', id: 'delete' },
        { label: 'CREATE TABLE', id: 'create_table' },
        { label: 'ALTER TABLE', id: 'alter_table' },
      ],
      value: () => 'select',
    },
    // Visual Builder - SELECT options
    {
      id: 'selectTables',
      title: 'Tables',
      type: 'short-input',
      layout: 'full',
      placeholder: 'users, orders, products',
      condition: { 
        field: 'queryMode', 
        value: 'visual',
        and: { field: 'operation', value: 'select' },
      },
      required: true,
      description: 'Comma-separated list of table names',
    },
    {
      id: 'selectColumns',
      title: 'Select Columns',
      type: 'long-input',
      layout: 'full',
      placeholder: 'users.id, users.name, orders.total, COUNT(*) as order_count',
      condition: { 
        field: 'queryMode', 
        value: 'visual',
        and: { field: 'operation', value: 'select' },
      },
      required: true,
      rows: 3,
      description: 'Columns to select (use * for all)',
    },
    {
      id: 'joins',
      title: 'JOIN Clauses',
      type: 'table',
      layout: 'full',
      columns: ['Type', 'Table', 'Condition'],
      condition: { 
        field: 'queryMode', 
        value: 'visual',
        and: { field: 'operation', value: 'select' },
      },
      description: 'JOIN operations (INNER, LEFT, RIGHT, FULL)',
    },
    {
      id: 'whereConditions',
      title: 'WHERE Conditions',
      type: 'long-input',
      layout: 'full',
      placeholder: 'users.active = true AND orders.created_at > ?',
      condition: { 
        field: 'queryMode', 
        value: 'visual',
        and: { field: 'operation', value: ['select', 'update', 'delete'] },
      },
      rows: 2,
      description: 'WHERE clause conditions',
    },
    {
      id: 'groupBy',
      title: 'GROUP BY',
      type: 'short-input',
      layout: 'half',
      placeholder: 'users.id, users.name',
      condition: { 
        field: 'queryMode', 
        value: 'visual',
        and: { field: 'operation', value: 'select' },
      },
      description: 'GROUP BY columns',
    },
    {
      id: 'having',
      title: 'HAVING',
      type: 'short-input',
      layout: 'half',
      placeholder: 'COUNT(*) > 5',
      condition: { 
        field: 'queryMode', 
        value: 'visual',
        and: { field: 'operation', value: 'select' },
      },
      description: 'HAVING clause for grouped results',
    },
    {
      id: 'orderBy',
      title: 'ORDER BY',
      type: 'short-input',
      layout: 'half',
      placeholder: 'created_at DESC, name ASC',
      condition: { 
        field: 'queryMode', 
        value: 'visual',
        and: { field: 'operation', value: 'select' },
      },
      description: 'ORDER BY columns with direction',
    },
    {
      id: 'limit',
      title: 'LIMIT',
      type: 'short-input',
      layout: 'half',
      placeholder: '100',
      condition: { 
        field: 'queryMode', 
        value: 'visual',
        and: { field: 'operation', value: 'select' },
      },
      description: 'Maximum number of rows to return',
    },
    // Visual Builder - INSERT options
    {
      id: 'insertTable',
      title: 'Table Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'users',
      condition: { 
        field: 'queryMode', 
        value: 'visual',
        and: { field: 'operation', value: 'insert' },
      },
      required: true,
    },
    {
      id: 'insertData',
      title: 'Insert Data',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: `{
  "name": "John Doe",
  "email": "john@example.com",
  "active": true
}`,
      condition: { 
        field: 'queryMode', 
        value: 'visual',
        and: { field: 'operation', value: 'insert' },
      },
      required: true,
      description: 'Data to insert as JSON object or array',
    },
    // Visual Builder - UPDATE options
    {
      id: 'updateTable',
      title: 'Table Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'users',
      condition: { 
        field: 'queryMode', 
        value: 'visual',
        and: { field: 'operation', value: 'update' },
      },
      required: true,
    },
    {
      id: 'updateData',
      title: 'Update Data',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: `{
  "name": "Jane Doe",
  "email": "jane@example.com",
  "updated_at": "NOW()"
}`,
      condition: { 
        field: 'queryMode', 
        value: 'visual',
        and: { field: 'operation', value: 'update' },
      },
      required: true,
      description: 'Data to update as JSON object',
    },
    // Visual Builder - DELETE options
    {
      id: 'deleteTable',
      title: 'Table Name',
      type: 'short-input',
      layout: 'full',
      placeholder: 'users',
      condition: { 
        field: 'queryMode', 
        value: 'visual',
        and: { field: 'operation', value: 'delete' },
      },
      required: true,
    },
    // Raw SQL mode
    {
      id: 'rawQuery',
      title: 'SQL Query',
      type: 'code',
      layout: 'full',
      language: 'sql',
      placeholder: `SELECT 
  u.id, 
  u.name, 
  u.email,
  COUNT(o.id) as order_count,
  SUM(o.total) as total_spent
FROM users u
LEFT JOIN orders o ON u.id = o.user_id
WHERE u.active = true
GROUP BY u.id, u.name, u.email
HAVING COUNT(o.id) > 0
ORDER BY total_spent DESC
LIMIT 100;`,
      condition: { field: 'queryMode', value: 'raw' },
      required: true,
      rows: 12,
      wandConfig: {
        enabled: true,
        maintainHistory: true,
        prompt: `You are an expert SQL developer. Generate optimized SQL queries based on the user's requirements.

Current context: {context}
Database type: {databaseType}

Generate ONLY the SQL query with proper formatting and optimization for the specified database type.

Guidelines:
1. Use proper SQL syntax for the target database
2. Include appropriate indexes and performance optimizations
3. Use parameterized queries where applicable
4. Format queries with proper indentation
5. Include helpful comments for complex logic

Return only the SQL query, no explanations.`,
        placeholder: 'Describe the SQL query you need...',
        generationType: 'sql-query',
      },
    },
    // Template Query mode
    {
      id: 'queryTemplate',
      title: 'Query Template',
      type: 'dropdown',
      layout: 'full',
      condition: { field: 'queryMode', value: 'template' },
      options: [
        { label: 'User Analytics', id: 'user_analytics' },
        { label: 'Sales Report', id: 'sales_report' },
        { label: 'Product Performance', id: 'product_performance' },
        { label: 'Customer Segmentation', id: 'customer_segmentation' },
        { label: 'Inventory Status', id: 'inventory_status' },
        { label: 'Financial Summary', id: 'financial_summary' },
      ],
      required: true,
    },
    {
      id: 'templateParams',
      title: 'Template Parameters',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: `{
  "start_date": "2024-01-01",
  "end_date": "2024-12-31",
  "status": "active",
  "limit": 100
}`,
      condition: { field: 'queryMode', value: 'template' },
      description: 'Parameters for the selected template',
    },
    {
      id: 'queryParameters',
      title: 'Query Parameters',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: `{
  "user_id": 123,
  "start_date": "2024-01-01",
  "status": "active"
}`,
      description: 'Parameters to bind to the query (for ? placeholders)',
    },
    {
      id: 'connectionPool',
      title: 'Use Connection Pooling',
      type: 'switch',
      layout: 'half',
      description: 'Enable connection pooling for better performance',
      value: () => true,
    },
    {
      id: 'transaction',
      title: 'Use Transaction',
      type: 'switch',
      layout: 'half',
      description: 'Wrap query in a transaction',
    },
    {
      id: 'queryTimeout',
      title: 'Query Timeout (seconds)',
      type: 'slider',
      layout: 'half',
      min: 5,
      max: 300,
      step: 5,
      value: () => '30',
      description: 'Maximum query execution time',
    },
    {
      id: 'maxRows',
      title: 'Max Rows Limit',
      type: 'slider',
      layout: 'half',
      min: 100,
      max: 10000,
      step: 100,
      value: () => '1000',
      description: 'Safety limit for maximum rows returned',
    },
  ],
  tools: {
    access: ['sql_query_builder'],
  },
  inputs: {
    databaseType: { type: 'string', description: 'Type of database' },
    connectionString: { type: 'string', description: 'Database connection string' },
    useIndividualFields: { type: 'boolean', description: 'Use individual connection fields' },
    host: { type: 'string', description: 'Database host' },
    port: { type: 'string', description: 'Database port' },
    database: { type: 'string', description: 'Database name' },
    username: { type: 'string', description: 'Database username' },
    password: { type: 'string', description: 'Database password' },
    queryMode: { type: 'string', description: 'Query building mode' },
    operation: { type: 'string', description: 'SQL operation type' },
    selectTables: { type: 'string', description: 'Tables for SELECT' },
    selectColumns: { type: 'string', description: 'Columns to select' },
    joins: { type: 'json', description: 'JOIN operations' },
    whereConditions: { type: 'string', description: 'WHERE clause' },
    groupBy: { type: 'string', description: 'GROUP BY columns' },
    having: { type: 'string', description: 'HAVING clause' },
    orderBy: { type: 'string', description: 'ORDER BY clause' },
    limit: { type: 'string', description: 'LIMIT clause' },
    insertTable: { type: 'string', description: 'Table for INSERT' },
    insertData: { type: 'json', description: 'Data to insert' },
    updateTable: { type: 'string', description: 'Table for UPDATE' },
    updateData: { type: 'json', description: 'Data to update' },
    deleteTable: { type: 'string', description: 'Table for DELETE' },
    rawQuery: { type: 'string', description: 'Raw SQL query' },
    queryTemplate: { type: 'string', description: 'Pre-built query template' },
    templateParams: { type: 'json', description: 'Template parameters' },
    queryParameters: { type: 'json', description: 'Query bind parameters' },
    connectionPool: { type: 'boolean', description: 'Use connection pooling' },
    transaction: { type: 'boolean', description: 'Use transaction' },
    queryTimeout: { type: 'number', description: 'Query timeout in seconds' },
    maxRows: { type: 'number', description: 'Maximum rows limit' },
  },
  outputs: {
    rows: { type: 'array', description: 'Query result rows' },
    rowCount: { type: 'number', description: 'Number of rows returned/affected' },
    columns: { type: 'array', description: 'Column metadata' },
    executionTime: { type: 'number', description: 'Query execution time in milliseconds' },
    generatedSql: { type: 'string', description: 'Generated SQL query' },
    affectedRows: { type: 'number', description: 'Number of rows affected (INSERT/UPDATE/DELETE)' },
    insertId: { type: 'string', description: 'ID of inserted row (if applicable)' },
    warnings: { type: 'array', description: 'Database warnings' },
    metadata: { type: 'json', description: 'Additional query metadata' },
    error: { type: 'string', description: 'Error message if query failed' },
  },
}