import { ChartBarIcon } from '@/components/icons'
import type { BlockConfig } from '@/blocks/types'
import type { MonitorResponse } from '@/tools/monitor/types'

export const SystemMonitorBlock: BlockConfig<MonitorResponse> = {
  type: 'system_monitor',
  name: 'System Monitor',
  description: 'Comprehensive system monitoring with alerts and analytics',
  longDescription:
    'Monitor system health, performance metrics, and business KPIs with real-time alerting, dashboard creation, and comprehensive analytics. Support for custom metrics and multi-source monitoring.',
  docsLink: 'https://docs.sim.ai/blocks/system-monitor',
  category: 'blocks',
  bgColor: '#10B981',
  icon: ChartBarIcon,
  subBlocks: [
    {
      id: 'monitorType',
      title: 'Monitor Type',
      type: 'dropdown',
      layout: 'full',
      required: true,
      options: [
        { label: 'System Health', id: 'system' },
        { label: 'Application Performance', id: 'application' },
        { label: 'API Monitoring', id: 'api' },
        { label: 'Database Monitoring', id: 'database' },
        { label: 'Website Monitoring', id: 'website' },
        { label: 'Business Metrics', id: 'business' },
        { label: 'Custom Metrics', id: 'custom' },
      ],
    },
    // System Health Monitoring
    {
      id: 'systemMetrics',
      title: 'System Metrics to Monitor',
      type: 'checkbox-list',
      layout: 'full',
      condition: { field: 'monitorType', value: 'system' },
      options: [
        { label: 'CPU Usage', id: 'cpu' },
        { label: 'Memory Usage', id: 'memory' },
        { label: 'Disk Usage', id: 'disk' },
        { label: 'Network I/O', id: 'network' },
        { label: 'Load Average', id: 'load' },
        { label: 'Process Count', id: 'processes' },
        { label: 'Uptime', id: 'uptime' },
        { label: 'Temperature', id: 'temperature' },
      ],
      value: () => ['cpu', 'memory', 'disk'],
      required: true,
    },
    {
      id: 'serverEndpoints',
      title: 'Server Endpoints',
      type: 'table',
      layout: 'full',
      columns: ['Server Name', 'Host/IP', 'SSH Key/Credentials', 'Port'],
      condition: { field: 'monitorType', value: 'system' },
      description: 'Servers to monitor (requires SSH access)',
    },
    // Application Performance Monitoring
    {
      id: 'appMetrics',
      title: 'Application Metrics',
      type: 'checkbox-list',
      layout: 'full',
      condition: { field: 'monitorType', value: 'application' },
      options: [
        { label: 'Response Time', id: 'response_time' },
        { label: 'Throughput (RPS)', id: 'throughput' },
        { label: 'Error Rate', id: 'error_rate' },
        { label: 'Active Users', id: 'active_users' },
        { label: 'Queue Length', id: 'queue_length' },
        { label: 'Memory Leaks', id: 'memory_leaks' },
        { label: 'Cache Hit Rate', id: 'cache_hit' },
        { label: 'Database Connections', id: 'db_connections' },
      ],
      value: () => ['response_time', 'error_rate', 'throughput'],
      required: true,
    },
    {
      id: 'appEndpoints',
      title: 'Application Endpoints',
      type: 'table',
      layout: 'full',
      columns: ['Name', 'URL', 'Method', 'Auth Token', 'Expected Response'],
      condition: { field: 'monitorType', value: 'application' },
      description: 'Application endpoints to monitor',
    },
    // API Monitoring
    {
      id: 'apiEndpoints',
      title: 'API Endpoints',
      type: 'table',
      layout: 'full',
      columns: ['API Name', 'URL', 'Method', 'Headers', 'Expected Status', 'Timeout'],
      condition: { field: 'monitorType', value: 'api' },
      required: true,
      description: 'API endpoints to monitor for availability and performance',
    },
    {
      id: 'apiChecks',
      title: 'API Health Checks',
      type: 'checkbox-list',
      layout: 'full',
      condition: { field: 'monitorType', value: 'api' },
      options: [
        { label: 'Availability Check', id: 'availability' },
        { label: 'Response Time', id: 'response_time' },
        { label: 'Status Code Validation', id: 'status_code' },
        { label: 'Response Content Validation', id: 'content' },
        { label: 'SSL Certificate Check', id: 'ssl_cert' },
        { label: 'Rate Limiting Check', id: 'rate_limit' },
      ],
      value: () => ['availability', 'response_time', 'status_code'],
    },
    // Database Monitoring
    {
      id: 'databaseType',
      title: 'Database Type',
      type: 'dropdown',
      layout: 'half',
      condition: { field: 'monitorType', value: 'database' },
      options: [
        { label: 'PostgreSQL', id: 'postgresql' },
        { label: 'MySQL', id: 'mysql' },
        { label: 'MongoDB', id: 'mongodb' },
        { label: 'Redis', id: 'redis' },
        { label: 'Elasticsearch', id: 'elasticsearch' },
        { label: 'SQL Server', id: 'sqlserver' },
      ],
      required: true,
    },
    {
      id: 'dbConnectionString',
      title: 'Database Connection',
      type: 'long-input',
      layout: 'full',
      placeholder: 'postgresql://username:password@host:port/database',
      condition: { field: 'monitorType', value: 'database' },
      password: true,
      required: true,
      rows: 2,
    },
    {
      id: 'dbMetrics',
      title: 'Database Metrics',
      type: 'checkbox-list',
      layout: 'full',
      condition: { field: 'monitorType', value: 'database' },
      options: [
        { label: 'Connection Count', id: 'connections' },
        { label: 'Query Performance', id: 'query_perf' },
        { label: 'Slow Queries', id: 'slow_queries' },
        { label: 'Database Size', id: 'db_size' },
        { label: 'Index Usage', id: 'index_usage' },
        { label: 'Lock Waits', id: 'lock_waits' },
        { label: 'Replication Lag', id: 'replication_lag' },
        { label: 'Cache Hit Ratio', id: 'cache_hit_ratio' },
      ],
      value: () => ['connections', 'query_perf', 'slow_queries'],
    },
    // Website Monitoring
    {
      id: 'websiteUrls',
      title: 'Website URLs',
      type: 'table',
      layout: 'full',
      columns: ['Name', 'URL', 'Check Type', 'Expected Text/Element', 'User Agent'],
      condition: { field: 'monitorType', value: 'website' },
      required: true,
      description: 'Websites to monitor for uptime and performance',
    },
    {
      id: 'websiteChecks',
      title: 'Website Checks',
      type: 'checkbox-list',
      layout: 'full',
      condition: { field: 'monitorType', value: 'website' },
      options: [
        { label: 'HTTP Status Check', id: 'http_status' },
        { label: 'Page Load Time', id: 'load_time' },
        { label: 'Content Validation', id: 'content_check' },
        { label: 'SSL Certificate', id: 'ssl_check' },
        { label: 'DNS Resolution', id: 'dns_check' },
        { label: 'Page Size', id: 'page_size' },
        { label: 'SEO Metrics', id: 'seo_metrics' },
      ],
      value: () => ['http_status', 'load_time', 'ssl_check'],
    },
    // Business Metrics Monitoring
    {
      id: 'businessSources',
      title: 'Data Sources',
      type: 'table',
      layout: 'full',
      columns: ['Source Name', 'Type', 'Connection/API', 'Query/Endpoint'],
      condition: { field: 'monitorType', value: 'business' },
      required: true,
      description: 'Data sources for business metrics (databases, APIs, files)',
    },
    {
      id: 'businessMetrics',
      title: 'Business Metrics Configuration',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: `{
  "metrics": [
    {
      "name": "daily_revenue",
      "query": "SELECT SUM(amount) FROM orders WHERE DATE(created_at) = CURRENT_DATE",
      "target": 10000,
      "unit": "USD",
      "threshold": {"warning": 8000, "critical": 5000}
    },
    {
      "name": "active_users",
      "query": "SELECT COUNT(DISTINCT user_id) FROM sessions WHERE last_activity > NOW() - INTERVAL 1 HOUR",
      "target": 500,
      "unit": "users",
      "threshold": {"warning": 300, "critical": 100}
    }
  ]
}`,
      condition: { field: 'monitorType', value: 'business' },
      required: true,
      rows: 15,
      description: 'Business KPIs and their monitoring configuration',
    },
    // Custom Metrics Monitoring
    {
      id: 'customMetrics',
      title: 'Custom Metrics',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: `{
  "metrics": [
    {
      "name": "custom_metric_1",
      "type": "http",
      "url": "https://api.example.com/metrics",
      "method": "GET",
      "headers": {"Authorization": "Bearer token"},
      "jsonPath": "$.data.value",
      "unit": "count",
      "threshold": {"warning": 100, "critical": 200}
    },
    {
      "name": "file_count",
      "type": "file",
      "path": "/var/log/*.log",
      "operation": "count",
      "threshold": {"warning": 1000, "critical": 5000}
    }
  ]
}`,
      condition: { field: 'monitorType', value: 'custom' },
      required: true,
      rows: 15,
      description: 'Custom metrics with collection methods',
    },
    {
      id: 'checkInterval',
      title: 'Check Interval',
      type: 'dropdown',
      layout: 'half',
      required: true,
      options: [
        { label: '30 seconds', id: '30s' },
        { label: '1 minute', id: '1m' },
        { label: '5 minutes', id: '5m' },
        { label: '15 minutes', id: '15m' },
        { label: '30 minutes', id: '30m' },
        { label: '1 hour', id: '1h' },
      ],
      value: () => '5m',
      description: 'How often to check metrics',
    },
    {
      id: 'dataRetention',
      title: 'Data Retention (days)',
      type: 'slider',
      layout: 'half',
      min: 1,
      max: 365,
      step: 1,
      value: () => '30',
      description: 'How long to keep monitoring data',
    },
    // Alerting Configuration
    {
      id: 'enableAlerts',
      title: 'Enable Alerting',
      type: 'switch',
      layout: 'half',
      description: 'Send alerts when thresholds are exceeded',
      value: () => true,
    },
    {
      id: 'alertChannels',
      title: 'Alert Channels',
      type: 'checkbox-list',
      layout: 'full',
      condition: { field: 'enableAlerts', value: true },
      options: [
        { label: 'Email', id: 'email' },
        { label: 'Slack', id: 'slack' },
        { label: 'Teams', id: 'teams' },
        { label: 'SMS', id: 'sms' },
        { label: 'Webhook', id: 'webhook' },
        { label: 'PagerDuty', id: 'pagerduty' },
      ],
      value: () => ['email'],
      required: true,
    },
    {
      id: 'alertConfig',
      title: 'Alert Configuration',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: `{
  "email": {
    "recipients": ["admin@company.com", "ops-team@company.com"],
    "subject": "{{severity}} Alert: {{metric_name}}",
    "template": "default"
  },
  "slack": {
    "webhook": "https://hooks.slack.com/services/...",
    "channel": "#alerts",
    "username": "MonitorBot"
  },
  "escalation": {
    "enabled": true,
    "levels": [
      {"delay": "5m", "channels": ["email"]},
      {"delay": "15m", "channels": ["slack", "email"]},
      {"delay": "30m", "channels": ["sms", "pagerduty"]}
    ]
  }
}`,
      condition: { field: 'enableAlerts', value: true },
      rows: 15,
      description: 'Alert channel configuration and escalation',
    },
    {
      id: 'thresholds',
      title: 'Global Thresholds',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: `{
  "cpu_usage": {"warning": 70, "critical": 90},
  "memory_usage": {"warning": 80, "critical": 95},
  "disk_usage": {"warning": 85, "critical": 95},
  "response_time": {"warning": 1000, "critical": 5000},
  "error_rate": {"warning": 5, "critical": 10}
}`,
      description: 'Default thresholds for common metrics (percentage or absolute values)',
    },
    {
      id: 'dashboardEnabled',
      title: 'Create Dashboard',
      type: 'switch',
      layout: 'half',
      description: 'Generate real-time monitoring dashboard',
      value: () => true,
    },
    {
      id: 'dashboardConfig',
      title: 'Dashboard Configuration',
      type: 'code',
      layout: 'full',
      language: 'json',
      placeholder: `{
  "title": "System Monitoring Dashboard",
  "refreshInterval": "30s",
  "layout": "grid",
  "widgets": [
    {
      "type": "gauge",
      "metric": "cpu_usage",
      "title": "CPU Usage",
      "size": "small"
    },
    {
      "type": "line_chart",
      "metrics": ["response_time", "throughput"],
      "title": "Performance Trends",
      "timeRange": "24h",
      "size": "large"
    },
    {
      "type": "status_list",
      "metrics": ["all_endpoints"],
      "title": "Service Status",
      "size": "medium"
    }
  ]
}`,
      condition: { field: 'dashboardEnabled', value: true },
      rows: 15,
      description: 'Dashboard layout and widget configuration',
    },
    {
      id: 'reportingEnabled',
      title: 'Enable Reporting',
      type: 'switch',
      layout: 'half',
      description: 'Generate periodic monitoring reports',
    },
    {
      id: 'reportSchedule',
      title: 'Report Schedule',
      type: 'dropdown',
      layout: 'half',
      condition: { field: 'reportingEnabled', value: true },
      options: [
        { label: 'Daily', id: 'daily' },
        { label: 'Weekly', id: 'weekly' },
        { label: 'Monthly', id: 'monthly' },
      ],
      value: () => 'weekly',
    },
  ],
  tools: {
    access: ['system_monitor'],
  },
  inputs: {
    monitorType: { type: 'string', description: 'Type of monitoring to perform' },
    systemMetrics: { type: 'json', description: 'System metrics to monitor' },
    serverEndpoints: { type: 'json', description: 'Server endpoints configuration' },
    appMetrics: { type: 'json', description: 'Application metrics to monitor' },
    appEndpoints: { type: 'json', description: 'Application endpoints configuration' },
    apiEndpoints: { type: 'json', description: 'API endpoints to monitor' },
    apiChecks: { type: 'json', description: 'API health check configuration' },
    databaseType: { type: 'string', description: 'Type of database to monitor' },
    dbConnectionString: { type: 'string', description: 'Database connection string' },
    dbMetrics: { type: 'json', description: 'Database metrics to monitor' },
    websiteUrls: { type: 'json', description: 'Website URLs to monitor' },
    websiteChecks: { type: 'json', description: 'Website monitoring checks' },
    businessSources: { type: 'json', description: 'Business data sources' },
    businessMetrics: { type: 'json', description: 'Business metrics configuration' },
    customMetrics: { type: 'json', description: 'Custom metrics configuration' },
    checkInterval: { type: 'string', description: 'Monitoring check interval' },
    dataRetention: { type: 'number', description: 'Data retention period in days' },
    enableAlerts: { type: 'boolean', description: 'Enable alerting system' },
    alertChannels: { type: 'json', description: 'Alert notification channels' },
    alertConfig: { type: 'json', description: 'Alert configuration and escalation' },
    thresholds: { type: 'json', description: 'Global metric thresholds' },
    dashboardEnabled: { type: 'boolean', description: 'Enable dashboard creation' },
    dashboardConfig: { type: 'json', description: 'Dashboard configuration' },
    reportingEnabled: { type: 'boolean', description: 'Enable periodic reporting' },
    reportSchedule: { type: 'string', description: 'Report generation schedule' },
  },
  outputs: {
    monitorId: { type: 'string', description: 'Unique monitoring session ID' },
    status: { type: 'string', description: 'Current monitoring status' },
    metrics: { type: 'json', description: 'Current metric values' },
    alerts: { type: 'array', description: 'Active alerts and notifications' },
    healthStatus: { type: 'string', description: 'Overall system health status' },
    dashboardUrl: { type: 'string', description: 'URL to monitoring dashboard' },
    lastCheck: { type: 'string', description: 'Timestamp of last check' },
    nextCheck: { type: 'string', description: 'Timestamp of next scheduled check' },
    uptime: { type: 'number', description: 'System uptime percentage' },
    responseTime: { type: 'number', description: 'Average response time' },
    errorRate: { type: 'number', description: 'Current error rate percentage' },
    trends: { type: 'json', description: 'Metric trends and analysis' },
    recommendations: { type: 'array', description: 'System optimization recommendations' },
    reportUrls: { type: 'array', description: 'URLs to generated reports' },
    error: { type: 'string', description: 'Error message if monitoring failed' },
  },
}